/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var p,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};q.Symbol||(q.Symbol=da)}var da=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function ea(){ba();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(this)}});ea=function(){}}function fa(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){ea();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ia(a){ea();ba();ea();var b=a[Symbol.iterator];return b?b.call(a):fa(a)}
function ja(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(A)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!h(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=m(document,"link[rel=import]:not([import-dependency])"),
c=b.length;c?n(b,function(b){return g(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function g(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);La&&"style"===a.localName||a.addEventListener("error",c)}}function h(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.a={};this.b=0;this.c=new MutationObserver(function(b){return a.Ea(b)});this.c.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a){n(m(a,"template"),function(a){n(m(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),
function(a){var b=document.createElement("script");n(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});l(a.content)})}function m(a,b){return a.childNodes.length?a.querySelectorAll(b):V}function n(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var x=document.createElement("link"),A="import"in x,V=x.querySelectorAll("*"),Ma=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",
{get:function(){return Ma||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Ed=/(url\()([^)]*)(\))/g,Fd=/(@import[\s]+(?!url\())([^;]*)(;)/g,Gd=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,E={za:function(a,b){a.href&&a.setAttribute("href",E.R(a.getAttribute("href"),b));a.src&&a.setAttribute("src",E.R(a.getAttribute("src"),b));if("style"===a.localName){var c=E.ja(a.textContent,b,Ed);a.textContent=E.ja(c,b,Fd)}},ja:function(a,b,c){return a.replace(c,
function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=E.R(a,b));return c+"'"+a+"'"+e})},R:function(a,b){if(void 0===E.W){E.W=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";E.W="http://a/c%20d"===c.href}catch(nf){}}if(E.W)return(new URL(a,b)).href;c=E.ra;c||(c=document.implementation.createHTMLDocument("temp"),E.ra=c,c.ba=c.createElement("base"),c.head.appendChild(c.ba),c.aa=c.createElement("a"));c.ba.href=b;c.aa.href=a;return c.aa.href||a}},Ib={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=
a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,Ib.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},La=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);
k.prototype.loadImports=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){return b.o(a)})};k.prototype.o=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.__import=d,this.j(a))}else this.b++,this.a[c]="pending",Ib.load(c,function(a,d){a=b.Fa(a,d||c);b.a[c]=a;b.b--;b.loadImports(a);b.B()},function(){b.a[c]=null;b.b--;b.B()})};k.prototype.Fa=function(a,b){if(!a)return document.createDocumentFragment();La&&(a=a.replace(Gd,function(a,b,c){return-1===
a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,l(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=E.R(c.getAttribute("href"),b),c.removeAttribute("href");c=m(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');
var d=0;n(c,function(a){g(a);E.za(a,b);a.setAttribute("import-dependency","");if("script"===a.localName&&!a.src&&a.textContent){if("module"===a.type)throw Error("Inline module scripts are not supported in HTML Imports.");a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n")));a.textContent="";d++}});return a};k.prototype.B=function(){var a=this;if(!this.b){this.c.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&
b&&(a.loadImports(document),a.b||(a.c.observe(document.head,{childList:!0,subtree:!0}),a.ga()))};this.Ha(function(){c=!0;d()});this.Ga(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){var c=b.a[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),a.appendChild(c))})};k.prototype.Ga=function(a){function b(e){if(e<d){var f=c[e],h=document.createElement("script");f.removeAttribute("import-dependency");
n(f.attributes,function(a){return h.setAttribute(a.name,a.value)});Ma=h;f.parentNode.replaceChild(h,f);g(h,function(){Ma=null;b(e+1)})}else a()}var c=m(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.Ha=function(a){var b=m(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=La&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");n(b,function(b){g(b,function(){b.removeAttribute("import-dependency");0===--d&&
a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.ga=function(){var a=this,b=m(document,"link[rel=import]");n(b,function(b){return a.j(b)},!0)};k.prototype.j=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState=
"complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.Ea=function(a){var b=this;n(a,function(a){return n(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(h(a)?b.o(a):b.loadImports(a))})})};var Na=null;if(A)x=m(document,"link[rel=import]"),n(x,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),x=function(a){a=a.target;h(a)&&(a.__loaded=!0)},document.addEventListener("load",x,!0),document.addEventListener("error",
x,!0);else{var ca=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!ca||ca.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=h(this)?this:c(this);return a?a.href:ca&&ca.get?ca.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){Na=new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",
{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=A;a.whenReady=f;a.importForElement=c;a.loadImports=function(a){Na&&Na.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function ka(){this.ia=this.root=null;this.O=!1;this.w=this.K=this.X=this.assignedSlot=this.assignedNodes=this.C=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.F=void 0;this.na=this.da=!1;this.J={}}ka.prototype.toJSON=function(){return{}};function r(a){a.U||(a.U=new ka);return a.U}function t(a){return a&&a.U};var u=window.ShadyDOM||{};u.Ba=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var la=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");u.s=!!(la&&la.configurable&&la.get);u.Y=u.force||!u.Ba;var ma=navigator.userAgent.match("Trident"),na=navigator.userAgent.match("Edge");void 0===u.la&&(u.la=u.s&&(ma||na));function v(a){return(a=t(a))&&void 0!==a.firstChild}function w(a){return"ShadyRoot"===a.ta}function y(a){a=a.getRootNode();if(w(a))return a}
var z=Element.prototype,oa=z.matches||z.matchesSelector||z.mozMatchesSelector||z.msMatchesSelector||z.oMatchesSelector||z.webkitMatchesSelector;function pa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=e,g=a,h=Object.getOwnPropertyDescriptor(b,f);h&&Object.defineProperty(g,f,h)}}function qa(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)pa(a,c[d]);return a}function ra(a,b){for(var c in b)a[c]=b[c]}
var sa=document.createTextNode(""),ta=0,ua=[];(new MutationObserver(function(){for(;ua.length;)try{ua.shift()()}catch(a){throw sa.textContent=ta++,a;}})).observe(sa,{characterData:!0});function va(a){ua.push(a);sa.textContent=ta++}var wa=!!document.contains;function xa(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function ya(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ia(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var za=[],Aa;function Ba(a){Aa||(Aa=!0,va(Ca));za.push(a)}function Ca(){Aa=!1;for(var a=!!za.length;za.length;)za.shift()();return a}Ca.list=za;function Da(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.N=new Set}function Ea(a){a.a||(a.a=!0,va(function(){a.flush()}))}Da.prototype.flush=function(){if(this.a){this.a=!1;var a=this.takeRecords();a.length&&this.N.forEach(function(b){b(a)})}};Da.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Fa(a,b){var c=r(a);c.C||(c.C=new Da);c.C.N.add(b);var d=c.C;return{sa:b,va:d,ua:a,takeRecords:function(){return d.takeRecords()}}}function Ga(a){var b=a&&a.va;b&&(b.N.delete(a.sa),b.N.size||(r(a.ua).C=null))}
function Ha(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var Ia=Element.prototype.insertBefore,Ja=Element.prototype.replaceChild,Ka=Element.prototype.removeChild,Oa=Element.prototype.setAttribute,Pa=Element.prototype.removeAttribute,Qa=Element.prototype.cloneNode,Ra=Document.prototype.importNode,Sa=Element.prototype.addEventListener,Ta=Element.prototype.removeEventListener,Ua=Window.prototype.addEventListener,Va=Window.prototype.removeEventListener,Wa=Element.prototype.dispatchEvent,Xa=Node.prototype.contains||HTMLElement.prototype.contains,Ya=Document.prototype.getElementById,
Za=Element.prototype.querySelector,$a=DocumentFragment.prototype.querySelector,ab=Document.prototype.querySelector,bb=Element.prototype.querySelectorAll,cb=DocumentFragment.prototype.querySelectorAll,db=Document.prototype.querySelectorAll,B={};B.appendChild=Element.prototype.appendChild;B.insertBefore=Ia;B.replaceChild=Ja;B.removeChild=Ka;B.setAttribute=Oa;B.removeAttribute=Pa;B.cloneNode=Qa;B.importNode=Ra;B.addEventListener=Sa;B.removeEventListener=Ta;B.La=Ua;B.Ma=Va;B.dispatchEvent=Wa;
B.contains=Xa;B.getElementById=Ya;B.Ua=Za;B.Xa=$a;B.Sa=ab;B.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Za.call(this,a);case Node.DOCUMENT_NODE:return ab.call(this,a);default:return $a.call(this,a)}};B.Va=bb;B.Ya=cb;B.Ta=db;B.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return bb.call(this,a);case Node.DOCUMENT_NODE:return db.call(this,a);default:return cb.call(this,a)}};var eb=/[&\u00A0"]/g,fb=/[&\u00A0<>]/g;function gb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function hb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var ib=hb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),jb=hb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function kb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var m=h.localName,n="<"+m,x=h.attributes,A=0;k=x[A];A++)n+=" "+k.name+'="'+k.value.replace(eb,gb)+'"';n+=">";h=ib[m]?n:n+kb(h,l)+"</"+m+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&jb[k.localName]?h:h.replace(fb,gb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var C=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),D=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function lb(a){var b=[];C.currentNode=a;for(a=C.firstChild();a;)b.push(a),a=C.nextSibling();return b}
var F={parentNode:function(a){C.currentNode=a;return C.parentNode()},firstChild:function(a){C.currentNode=a;return C.firstChild()},lastChild:function(a){C.currentNode=a;return C.lastChild()},previousSibling:function(a){C.currentNode=a;return C.previousSibling()},nextSibling:function(a){C.currentNode=a;return C.nextSibling()}};F.childNodes=lb;F.parentElement=function(a){D.currentNode=a;return D.parentNode()};F.firstElementChild=function(a){D.currentNode=a;return D.firstChild()};
F.lastElementChild=function(a){D.currentNode=a;return D.lastChild()};F.previousElementSibling=function(a){D.currentNode=a;return D.previousSibling()};F.nextElementSibling=function(a){D.currentNode=a;return D.nextSibling()};F.children=function(a){var b=[];D.currentNode=a;for(a=D.firstChild();a;)b.push(a),a=D.nextSibling();return ya(b)};F.innerHTML=function(a){return kb(a,function(a){return lb(a)})};
F.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var mb=u.s,nb=[Node.prototype,Element.prototype,HTMLElement.prototype];function G(a){var b;a:{for(b=0;b<nb.length;b++){var c=nb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var H=mb?{parentNode:G("parentNode"),firstChild:G("firstChild"),lastChild:G("lastChild"),previousSibling:G("previousSibling"),nextSibling:G("nextSibling"),childNodes:G("childNodes"),parentElement:G("parentElement"),previousElementSibling:G("previousElementSibling"),nextElementSibling:G("nextElementSibling"),innerHTML:G("innerHTML"),textContent:G("textContent"),firstElementChild:G("firstElementChild"),lastElementChild:G("lastElementChild"),children:G("children")}:{},ob=mb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},pb=mb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{},qb={ha:H,Wa:ob,Ra:pb,parentNode:function(a){return H.parentNode.get.call(a)},
firstChild:function(a){return H.firstChild.get.call(a)},lastChild:function(a){return H.lastChild.get.call(a)},previousSibling:function(a){return H.previousSibling.get.call(a)},nextSibling:function(a){return H.nextSibling.get.call(a)},childNodes:function(a){return Array.prototype.slice.call(H.childNodes.get.call(a))},parentElement:function(a){return H.parentElement.get.call(a)},previousElementSibling:function(a){return H.previousElementSibling.get.call(a)},nextElementSibling:function(a){return H.nextElementSibling.get.call(a)},
innerHTML:function(a){return H.innerHTML.get.call(a)},textContent:function(a){return H.textContent.get.call(a)},children:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return ob.children.get.call(a);case Node.DOCUMENT_NODE:return pb.children.get.call(a);default:return H.children.get.call(a)}},firstElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return ob.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return pb.firstElementChild.get.call(a);default:return H.firstElementChild.get.call(a)}},
lastElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return ob.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return pb.lastElementChild.get.call(a);default:return H.lastElementChild.get.call(a)}}};var I=u.la?qb:F;function rb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var sb=u.s,tb=document.implementation.createHTMLDocument("inert"),ub=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),vb=ub&&ub.get,wb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),xb={parentElement:{get:function(){var a=t(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:I.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=t(this);a=a&&a.parentNode;return void 0!==a?a:I.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=t(this);a=a&&a.nextSibling;return void 0!==a?a:I.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=t(this);a=a&&a.previousSibling;return void 0!==a?a:I.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=t(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return I.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
t(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return I.previousElementSibling(this)},configurable:!0}},yb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},zb={childNodes:{get:function(){if(v(this)){var a=t(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
I.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=t(this);a=a&&a.firstChild;return void 0!==a?a:I.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=t(this);a=a&&a.lastChild;return void 0!==a?a:I.lastChild(this)},configurable:!0},textContent:{get:function(){if(v(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return I.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!v(this)&&sb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&rb(this);qb.ha.textContent.set.call(this,a)}else rb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
t(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return I.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=t(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return I.lastElementChild(this)},configurable:!0},children:{get:function(){return v(this)?ya(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
I.children(this)},configurable:!0},innerHTML:{get:function(){return v(this)?kb("template"===this.localName?this.content:this):I.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;rb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==tb.namespaceURI?tb.createElementNS(this.namespaceURI,c):tb.createElement(c);sb?qb.ha.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
Ab={shadowRoot:{get:function(){var a=t(this);return a&&a.ia||null},configurable:!0}},Bb={activeElement:{get:function(){var a=wb&&wb.get?wb.get.call(document):u.s?void 0:document.activeElement;if(a&&a.nodeType){var b=!!w(this);if(this===document||b&&this.host!==a&&B.contains.call(this.host,a)){for(b=y(a);b&&b!==this;)a=b.host,b=y(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function J(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function K(a){J(a,xb);J(a,yb);J(a,zb);J(a,Bb)}
function Cb(){var a=Db.prototype;a.__proto__=DocumentFragment.prototype;J(a,xb,!0);J(a,zb,!0);J(a,Bb,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Eb=u.s?function(){}:function(a){var b=r(a);b.da||(b.da=!0,J(a,xb,!0),J(a,yb,!0))},Fb=u.s?function(){}:function(a){r(a).na||(J(a,zb,!0),J(a,Ab,!0))};var Gb=I.childNodes;function Hb(a,b,c){Eb(a);c=c||null;var d=r(a),e=r(b),f=c?r(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=t(d.previousSibling))f.nextSibling=a;if(f=t(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Jb(a){var b=r(a);if(void 0===b.firstChild){b.childNodes=null;var c=Gb(a);b.firstChild=c[0]||null;b.lastChild=c[c.length-1]||null;Fb(a);for(b=0;b<c.length;b++){var d=c[b],e=r(d);e.parentNode=a;e.nextSibling=c[b+1]||null;e.previousSibling=c[b-1]||null;Eb(d)}}};var Kb=I.parentNode;
function Lb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=t(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Kb(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Mb(b.parentNode,b);d=!0;var e,f;if(!b.__noInsertionPoint){if(f=e=y(a)){var g;"slot"===b.localName?g=[b]:b.querySelectorAll&&
(g=b.querySelectorAll("slot"));f=g&&g.length?g:void 0}if(f){g=e;var h=f;g.a=g.a||[];g.f=g.f||[];g.g=g.g||{};g.a.push.apply(g.a,h instanceof Array?h:ja(ia(h)))}}("slot"===a.localName||f)&&(e=e||y(a))&&L(e);if(v(a)){e=c;Fb(a);f=r(a);void 0!==f.firstChild&&(f.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(g=0;g<f.length;g++)Hb(f[g],a,e);e=r(b);f=void 0!==e.firstChild?null:void 0;e.firstChild=e.lastChild=f;e.childNodes=f}else Hb(b,a,e);e=t(a);Nb(a)?(L(e.root),d=!1):e.root&&
(d=!1)}d?(d=w(a)?a.host:a,c?(c=Ob(c),B.insertBefore.call(d,b,c)):B.appendChild.call(d,b)):b.ownerDocument!==a.ownerDocument&&a.ownerDocument.adoptNode(b);Pb(a,b);return b}
function Mb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=y(b),d=t(a);if(v(a)){var e=r(b),f=r(a);b===f.firstChild&&(f.firstChild=e.nextSibling);b===f.lastChild&&(f.lastChild=e.previousSibling);var g=e.previousSibling,h=e.nextSibling;g&&(r(g).nextSibling=h);h&&(r(h).previousSibling=g);e.parentNode=e.previousSibling=e.nextSibling=void 0;void 0!==f.childNodes&&(f.childNodes=null);if(Nb(a)){L(d.root);var k=!0}}Qb(b);if(c){(e=a&&"slot"===a.localName)&&
(k=!0);if(c.f){Rb(c);f=c.g;for(V in f)for(g=f[V],h=0;h<g.length;h++){var l=g[h];if(xa(b,l)){g.splice(h,1);var m=c.f.indexOf(l);0<=m&&c.f.splice(m,1);h--;m=t(l);if(l=m.w)for(var n=0;n<l.length;n++){var x=l[n],A=Sb(x);A&&B.removeChild.call(A,x)}m.w=[];m.assignedNodes=[];m=!0}}var V=m}else V=void 0;(V||e)&&L(c)}k||(k=w(a)?a.host:a,(!d.root&&"slot"!==b.localName||k===Kb(b))&&B.removeChild.call(k,b));Pb(a,null,b);return b}
function Qb(a){var b=t(a);if(b&&void 0!==b.F){b=a.childNodes;for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)Qb(e)}if(a=t(a))a.F=void 0}function Ob(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=t(a))&&b.w)&&b.length?b[0]:Ob(a.nextSibling));return b}function Nb(a){return(a=(a=t(a))&&a.root)&&Tb(a)}
function Ub(a,b){if("slot"===b)a=a.parentNode,Nb(a)&&L(t(a).root);else if("slot"===a.localName&&"name"===b&&(b=y(a))){if(b.f){Rb(b);var c=a.qa,d=Vb(a);if(d!==c){c=b.g[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.g[d]||(b.g[d]=[]);c.push(a);1<c.length&&(b.g[d]=Wb(c))}}L(b)}}function Pb(a,b,c){if(a=(a=t(a))&&a.C)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ea(a)}
function Xb(a){if(a&&a.nodeType){var b=r(a),c=b.F;void 0===c&&(w(a)?(c=a,b.F=c):(c=(c=a.parentNode)?Xb(c):a,B.contains.call(document.documentElement,a)&&(b.F=c)));return c}}function Yb(a,b,c){var d=[];Zb(a.childNodes,b,c,d);return d}function Zb(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,m=d,n=k(h);n&&m.push(h);l&&l(n)?h=n:(Zb(h.childNodes,k,l,m),h=void 0)}if(h)break}}var $b=null;
function ac(a,b,c){$b||($b=window.ShadyCSS&&window.ShadyCSS.ScopingShim);$b&&"class"===b?$b.setElementClass(a,c):(B.setAttribute.call(a,b,c),Ub(a,b))}function bc(a,b){if(a.ownerDocument!==document||"template"===a.localName)return B.importNode.call(document,a,b);var c=B.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=bc(a[b],!0),c.appendChild(d)}return c};var cc="__eventWrappers"+Date.now(),dc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),ec={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},fc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function gc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function hc(a,b){if(!w)return a;a=gc(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!w(f)||-1<g)return d}
var ic={get composed(){void 0===this.I&&(dc?this.I=dc(this):!1!==this.isTrusted&&(this.I=ec[this.type]));return this.I||!1},composedPath:function(){this.ca||(this.ca=gc(this.__target,this.composed));return this.ca},get target(){return hc(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.T)return null;this.ea||(this.ea=gc(this.T,!0));return hc(this.currentTarget||this.__previousCurrentTarget,this.ea)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);
this.S=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.S=this.ma=!0}};function jc(a){function b(b,d){b=new a(b,d);b.I=d&&!!d.composed;return b}ra(b,a);b.prototype=a.prototype;return b}var kc={focus:!0,blur:!0};function lc(a){return a.__target!==a.target||a.T!==a.relatedTarget}function mc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!lc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.ma);d++);}
function nc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];mc(a,d,"capture");if(a.S)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=t(d);f=f&&f.root;if(0===c||f&&f===e)if(mc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.S)break}}
function oc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,m=h.once,n=h.passive;if(b===h.node&&c===k&&d===l&&e===m&&f===n)return g}return-1}
function pc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?B.La:B.addEventListener;if(fc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.V||this,l=b[cc];if(l){if(-1<oc(l,k,a,f,g,h))return}else b[cc]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||qc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}e.__previousCurrentTarget=e.currentTarget;if(!w(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(lc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&
(f?(Object.defineProperty(e,"currentTarget",f),f=null):delete e.currentTarget);return h}};b[cc].push({node:k,type:a,capture:f,once:g,passive:h,Na:l});kc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function rc(a,b,c){if(b){var d=this instanceof Window?B.Ma:B.removeEventListener;if(fc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.V||this,k=void 0;var l=null;try{l=b[cc]}catch(m){}l&&(f=oc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Na,l.length||(b[cc]=void 0)));d.call(this,a,k||b,c);k&&kc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function sc(){for(var a in kc)window.addEventListener(a,function(a){a.__target||(qc(a),nc(a))},!0)}function qc(a){a.__target=a.target;a.T=a.relatedTarget;if(u.s){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Pa=b;pa(c,ic);b.__patchProto=c}a.__proto__=b.__patchProto}else pa(a,ic)}var tc=jc(window.Event),uc=jc(window.CustomEvent),vc=jc(window.MouseEvent);
function wc(){window.Event=tc;window.CustomEvent=uc;window.MouseEvent=vc;sc();if(!dc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function xc(a,b){return{index:a,G:[],M:b}}
function yc(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,m=0;m<k-g&&zc(a[--h],c[--l]);)m++;h=m}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=xc(e,0);f<d;)b.G.push(c[f++]);return[b]}if(f==d)return[xc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<h;m++)if(a[k+m-1]===c[g+l-1])b[l][m]=
b[l-1][m-1];else{var n=b[l-1][m]+1,x=b[l][m-1]+1;b[l][m]=n<x?n:x}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],m=b[k][g-1],n=l<m?l<h?l:h:m<h?m:h,n==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):n==l?(a.push(3),k--,d=l):(a.push(2),g--,d=m));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=xc(e,0));b.M++;e++;b.G.push(c[f]);f++;break;case 2:b||(b=xc(e,0));
b.M++;e++;break;case 3:b||(b=xc(e,0)),b.G.push(c[f]),f++}b&&k.push(b);return k}function zc(a,b){return a===b};var Sb=I.parentNode,Ac=I.childNodes,Bc={},M=u.deferConnectionCallbacks&&"loading"===document.readyState,Cc;function Dc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function Db(a,b,c){if(a!==Bc)throw new TypeError("Illegal constructor");this.ta="ShadyRoot";this.host=b;this.c=c&&c.mode;Jb(b);a=r(b);a.root=this;a.ia="closed"!==this.c?this:null;a=r(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.b=this.L=!1;this.a=this.g=this.f=null;L(this)}function L(a){a.L||(a.L=!0,Ba(function(){return Ec(a)}))}
function Ec(a){for(var b;a;){a.L&&(b=a);a:{var c=a;a=c.host.getRootNode();if(w(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
Db.prototype._renderRoot=function(){var a=M;M=!0;this.L=!1;if(this.f){Rb(this);for(var b=0,c;b<this.f.length;b++){c=this.f[b];var d=t(c),e=d.assignedNodes;d.assignedNodes=[];d.w=[];if(d.X=e)for(d=0;d<e.length;d++){var f=t(e[d]);f.K=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(c=this.host.firstChild;c;c=c.nextSibling)Fc(this,c);for(b=0;b<this.f.length;b++){c=this.f[b];e=t(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Fc(this,d,c);(d=(d=t(c.parentNode))&&d.root)&&
Tb(d)&&d._renderRoot();Gc(this,e.w,e.assignedNodes);if(d=e.X){for(f=0;f<d.length;f++)t(d[f]).K=null;e.X=null;d.length>e.assignedNodes.length&&(e.O=!0)}e.O&&(e.O=!1,Hc(this,c))}b=this.f;c=[];for(e=0;e<b.length;e++)d=b[e].parentNode,(f=t(d))&&f.root||!(0>c.indexOf(d))||c.push(d);for(b=0;b<c.length;b++){e=c[b];d=e===this?this.host:e;f=[];e=e.childNodes;for(var g=0;g<e.length;g++){var h=e[g];if("slot"==h.localName){h=t(h).w;for(var k=0;k<h.length;k++)f.push(h[k])}else f.push(h)}e=void 0;g=Ac(d);h=yc(f,
f.length,g,g.length);for(var l=k=0;k<h.length&&(e=h[k]);k++){for(var m=0,n;m<e.G.length&&(n=e.G[m]);m++)Sb(n)===d&&B.removeChild.call(d,n),g.splice(e.index+l,1);l-=e.M}for(l=0;l<h.length&&(e=h[l]);l++)for(k=g[e.index],m=e.index;m<e.index+e.M;m++)n=f[m],B.insertBefore.call(d,n,k),g.splice(m,0,n)}}if(!this.b)for(n=this.host.childNodes,c=0,b=n.length;c<b;c++)e=n[c],d=t(e),Sb(e)!==this.host||"slot"!==e.localName&&d.assignedSlot||B.removeChild.call(this.host,e);this.b=!0;M=a;Cc&&Cc()};
function Fc(a,b,c){var d=r(b),e=d.K;d.K=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(r(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(r(d.assignedSlot).O=!0)}function Gc(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=t(e).assignedNodes;f&&f.length&&Gc(a,b,f)}else b.push(c[d])}function Hc(a,b){B.dispatchEvent.call(b,new Event("slotchange"));b=t(b);b.assignedSlot&&Hc(a,b.assignedSlot)}
function Rb(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];Jb(e);Jb(e.parentNode);var f=Vb(e);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(e)):a.g[f]=[e];a.f.push(e)}if(c)for(var g in c)a.g[g]=Wb(a.g[g]);a.a=[]}}function Vb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.qa=b}function Wb(a){return a.sort(function(a,c){a=Dc(a);for(var b=Dc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Tb(a){Rb(a);return!(!a.f||!a.f.length)}
if(window.customElements&&u.Y){var Ic=new Map;Cc=function(){var a=Array.from(Ic);Ic.clear();a=ia(a);for(var b=a.next();!b.done;b=a.next()){b=ia(b.value);var c=b.next().value;b.next().value?c.oa():c.pa()}};M&&document.addEventListener("readystatechange",function(){M=!1;Cc()},{once:!0});var Jc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.oa=function(){M?Ic.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.pa=
function(){M?this.isConnected||Ic.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Kc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Kc.call(window.customElements,a,Jc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Lc(a){var b=a.getRootNode();w(b)&&Ec(b);return(a=t(a))&&a.assignedSlot||null}
var Mc={addEventListener:pc.bind(window),removeEventListener:rc.bind(window)},Nc={addEventListener:pc,removeEventListener:rc,appendChild:function(a){return Lb(this,a)},insertBefore:function(a,b){return Lb(this,a,b)},removeChild:function(a){return Mb(this,a)},replaceChild:function(a,b){Lb(this,a,b);Mb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=B.cloneNode.call(this,a);else if(b=B.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Xb(this)},contains:function(a){return xa(this,a)},dispatchEvent:function(a){Ca();return B.dispatchEvent.call(this,a)}};
Object.defineProperties(Nc,{isConnected:{get:function(){if(vb&&vb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(wa){if(B.contains.call(a,this))return!0}else if(a.documentElement&&B.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(w(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Oc={get assignedSlot(){return Lc(this)}},Pc={querySelector:function(a){return Yb(this,function(b){return oa.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(B.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Yb(this,function(b){return oa.call(b,a)})}},Qc={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();w(b)&&Ec(b);return(b=t(this))?
(a&&a.flatten?b.w:b.assignedNodes)||[]:[]}}},Rc=qa({setAttribute:function(a,b){ac(this,a,b)},removeAttribute:function(a){B.removeAttribute.call(this,a);Ub(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new Db(Bc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){ac(this,"slot",a)},get assignedSlot(){return Lc(this)}},Pc,Qc);Object.defineProperties(Rc,Ab);
var Sc=qa({importNode:function(a,b){return bc(a,b)},getElementById:function(a){return Yb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Pc);Object.defineProperties(Sc,{_activeElement:Bb.activeElement});
for(var Tc=HTMLElement.prototype.blur,Uc={blur:function(){var a=t(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Tc.call(this)}},N={},Vc=ia(Object.getOwnPropertyNames(Document.prototype)),Wc=Vc.next();!Wc.done;N={l:N.l},Wc=Vc.next())N.l=Wc.value,"on"===N.l.substring(0,2)&&Object.defineProperty(Uc,N.l,{set:function(a){return function(b){var c=r(this),d=a.l.substring(2);c.J[a.l]&&this.removeEventListener(d,c.J[a.l]);this.addEventListener(d,b,{});c.J[a.l]=b}}(N),get:function(a){return function(){var b=
t(this);return b&&b.J[a.l]}}(N),configurable:!0});var Xc={addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.V=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.V=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Yb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};
function O(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(u.Y){var ShadyDOM={inUse:u.Y,patch:function(a){Fb(a);Eb(a);return a},isShadyRoot:w,enqueue:Ba,flush:Ca,settings:u,filterMutations:Ha,observeChildren:Fa,unobserveChildren:Ga,nativeMethods:B,nativeTree:I,deferConnectionCallbacks:u.deferConnectionCallbacks};window.ShadyDOM=ShadyDOM;wc();var Yc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;O(Db.prototype,Xc);O(window.Node.prototype,Nc);O(window.Window.prototype,Mc);O(window.Text.prototype,Oc);O(window.DocumentFragment.prototype,
Pc);O(window.Element.prototype,Rc);O(window.Document.prototype,Sc);window.HTMLSlotElement&&O(window.HTMLSlotElement.prototype,Qc);O(Yc.prototype,Uc);u.s&&(K(window.Node.prototype),K(window.Text.prototype),K(window.DocumentFragment.prototype),K(window.Element.prototype),K(Yc.prototype),K(window.Document.prototype),window.HTMLSlotElement&&K(window.HTMLSlotElement.prototype));Cb();window.ShadowRoot=Db};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Zc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function $c(a){a=a.replace(ad,"").replace(bd,"");var b=cd,c=a,d=new Zc;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new Zc;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function cd(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=dd(c),c=c.replace(ed," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=fd:c.match(gd)&&(a.type=hd,a.keyframesName=a.selector.split(ed).pop()):a.type=0===c.indexOf("--")?id:jd);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)cd(f,
b);return a}function dd(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function kd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=kd(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(ld,"").replace(md,""),b=b.replace(nd,"").replace(od,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var jd=1,hd=7,fd=4,id=1E3,ad=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,bd=/@import[^;]*;/gim,ld=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,md=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,nd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,od=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,gd=/^@[^\s]*keyframes/,ed=/\s+/g;var P=!(window.ShadyDOM&&window.ShadyDOM.inUse),pd;function qd(a){pd=a&&a.shimcssproperties?!1:P||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?pd=window.ShadyCSS.nativeCss:window.ShadyCSS?(qd(window.ShadyCSS),window.ShadyCSS=void 0):qd(window.WebComponents&&window.WebComponents.flags);var Q=pd;var rd=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,sd=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,td=/(--[\w-]+)\s*([:,;)]|$)/gi,ud=/(animation\s*:)|(animation-name\s*:)/,vd=/@media\s(.*)/,wd=/\{[^}]*\}/g;var xd=new Set;function R(a,b){if(!a)return"";"string"===typeof a&&(a=$c(a));b&&S(a,b);return kd(a,Q)}function yd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=$c(a.textContent));return a.__cssRules||null}function zd(a){return!!a.parent&&a.parent.type===hd}function S(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===fd){var g=a.selector.match(vd);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===jd?b(a):c&&f===hd?c(a):f===id&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)S(h,b,c,d)}}}
function Ad(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Bd(e,c,d);return e}var T=null;function Cd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(T?T.nextSibling:null)||b.firstChild);return T=a}function Bd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);T?a.compareDocumentPosition(T)===Node.DOCUMENT_POSITION_PRECEDING&&(T=a):T=a}
function Dd(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function Hd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=Dd(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=Hd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Id(a,b){P?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function U(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,H:c}}function Jd(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=Dd(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b};function Kd(){}function Ld(a,b){var c=W;a.__styleScoped?a.__styleScoped=null:Md(c,a,function(a){Nd(a,b||"")})}function Md(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);if(b="template"===b.localName?(b.content||b.Qa||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)Md(a,b[d],c)}
function Nd(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Od);c?d&&(b=d.replace("style-scope","").replace(b,""),Id(a,b)):Id(a,(d?d+" ":"")+"style-scope "+b)}}function Pd(a,b,c){var d=W;a.__styleScoped?a.__styleScoped=null:Md(d,a,function(a){Nd(a,b,!0);Nd(a,c)})}function Qd(a,b){var c=W;a.__styleScoped?a.__styleScoped=null:Md(c,a,function(a){Nd(a,b||"",!0)})}
function Rd(a,b,c){var d=W,e=a.__cssBuild;P||"shady"===e?b=R(b,c):(a=U(a),b=Sd(d,b,a.is,a.H,c)+"\n\n");return b.trim()}function Sd(a,b,c,d,e){var f=Td(c,d);c=c?Ud+c:"";return R(b,function(b){b.c||(b.selector=b.i=Vd(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function Td(a,b){return b?"[is="+a+"]":a}function Vd(a,b,c,d,e){var f=Jd(b.selector);if(!zd(b)){b=0;for(var g=f.length,h;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(a){return!!a}).join(Wd)}
function Xd(a){return a.replace(Yd,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}function Zd(a){for(var b=[],c;c=a.match($d);){var d=c.index,e=Dd(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{$:a,matches:b}}function ae(a,b){var c=a.split("\ue000");return b.reduce(function(a,b,f){return a+b+c[f+1]},c[0])}
Kd.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=Yd.test(a);e&&(a=a.replace(Yd,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=Xd(a));var f=$d.test(a);if(f){var g=Zd(a);a=g.$;g=g.matches}a=a.replace(be,ce+" $1");a=a.replace(de,function(a,e,f){d||(a=ee(f,e,b,c),d=d||a.stop,e=a.ya,f=a.value);return e+f});f&&(a=ae(a,g));e&&(a=Xd(a));return a};
function ee(a,b,c,d){var e=a.indexOf(fe);0<=a.indexOf(ce)?a=ge(a,d):0!==e&&(a=c?he(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(ie,function(a,b){return" > "+b}))}a=a.replace(je,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,ya:b,stop:f}}function he(a,b){a=a.split(ke);a[0]+=b;return a.join(ke)}
function ge(a,b){var c=a.match(le);return(c=c&&c[2].trim()||"")?c[0].match(me)?a.replace(le,function(a,c,f){return b+f}):c.split(me)[0]===b?c:ne:a.replace(ce,b)}function oe(a){a.selector===pe&&(a.selector="html")}Kd.prototype.c=function(a){return a.match(ce)?"":a.match(fe)?this.b(a,qe):he(a.trim(),qe)};q.Object.defineProperties(Kd.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Yd=/:(nth[-\w]+)\(([^)]+)\)/,qe=":not(.style-scope)",Wd=",",de=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,me=/[[.:#*]/,ce=":host",pe=":root",fe="::slotted",be=new RegExp("^("+fe+")"),le=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ie=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,je=/(.*):dir\((?:(ltr|rtl))\)/,Ud=".",ke=":",Od="class",ne="should_not_match",$d=/:(?:matches|any|-(?:webkit|moz)-any)/,W=new Kd;function re(a,b,c,d){this.v=a||null;this.b=b||null;this.Z=c||[];this.D=null;this.H=d||"";this.a=this.m=this.A=null}function X(a){return a?a.__styleInfo:null}function se(a,b){return a.__styleInfo=b}re.prototype.c=function(){return this.v};re.prototype._getStyleRules=re.prototype.c;function te(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var ue=navigator.userAgent.match("Trident");function ve(){}function we(a){var b={},c=[],d=0;S(a,function(a){xe(a);a.index=d++;a=a.h.cssText;for(var c;c=td.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function xe(a){if(!a.h){var b={},c={};ye(a,c)&&(b.u=c,a.rules=null);b.cssText=a.parsedCssText.replace(wd,"").replace(rd,"");a.h=b}}function ye(a,b){var c=a.h;if(c){if(c.u)return Object.assign(b,c.u),!0}else{c=a.parsedCssText;for(var d;a=rd.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function ze(a,b,c){b&&(b=0<=b.indexOf(";")?Ae(a,b,c):Hd(b,function(b,e,f,g){if(!e)return b+g;(e=ze(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=ze(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function Ae(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){sd.lastIndex=0;if(f=sd.exec(e))e=ze(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=ze(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Be(a,b){var c={},d=[];S(a,function(a){a.h||xe(a);var e=a.i||a.parsedSelector;b&&a.h.u&&e&&te.call(b,e)&&(ye(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{u:c,key:d}}
function Ce(a,b,c,d){b.h||xe(b);if(b.h.u){var e=U(a);a=e.is;e=e.H;e=a?Td(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(b.i||(b.i=Vd(W,b,W.b,a?Ud+a:"",e)),c=b.i||e),d({$:c,Da:h,Za:g})}}
function De(a,b){var c={},d={},e=b&&b.__cssBuild;S(b,function(b){Ce(a,b,e,function(e){te.call(a.ga||a,e.$)&&(e.Da?ye(b,c):ye(b,d))})},null,!0);return{Ia:d,Ca:c}}
function Ee(a,b,c,d){var e=U(b),f=Td(e.is,e.H),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=X(b).v;var h=Fe(e,d);return Rd(b,e,function(b){var e="";b.h||xe(b);b.h.cssText&&(e=Ae(a,b.h.cssText,c));b.cssText=e;if(!P&&!zd(b)&&b.cssText){var k=e=b.cssText;null==b.fa&&(b.fa=ud.test(e));if(b.fa)if(null==b.P){b.P=[];for(var n in h)k=h[n],k=k(e),e!==k&&(e=k,b.P.push(n))}else{for(n=0;n<b.P.length;++n)k=h[b.P[n]],e=k(e);k=e}b.cssText=k;b.i=b.i||b.selector;e="."+d;
n=Jd(b.i);k=0;for(var x=n.length,A;k<x&&(A=n[k]);k++)n[k]=A.match(g)?A.replace(f,e):e+" "+A;b.selector=n.join(",")}})}function Fe(a,b){a=a.b;var c={};if(!P&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.j=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.i=f.i||f.selector;f.selector=f.i.replace(f.keyframesName,f.a);c[e.keyframesName]=Ge(e)}return c}function Ge(a){return function(b){return b.replace(a.j,a.a)}}
function He(a,b){var c=Ie,d=yd(a);a.textContent=R(d,function(a){var d=a.cssText=a.parsedCssText;a.h&&a.h.cssText&&(d=d.replace(ld,"").replace(md,""),a.cssText=Ae(c,d,b))})}q.Object.defineProperties(ve.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ie=new ve;var Je={},Ke=window.customElements;if(Ke&&!P){var Le=Ke.define;Ke.define=function(a,b,c){Je[a]||(Je[a]=Cd(a));Le.call(Ke,a,b,c)}};function Me(){this.cache={}}Me.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({u:b,styleElement:c,m:d});100<e.length&&e.shift();this.cache[a]=e};Me.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(e.u[g]!==b[g]){f=!1;break a}}f=!0}if(f)return e}};function Ne(){}
function Oe(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));g=h;h=g.indexOf(W.a);if((g=-1<h?g[h+1]:"")&&f===e.ownerDocument)Qd(e,g);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=
f.host))for(f=U(f).is,f!==g&&Pd(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+W.a+")"),f=0;f<e.length;f++)if(g=e[f],h=g.getRootNode().host)h=U(h).is,Nd(g,h)}}}}
if(!P){var Pe=new MutationObserver(Oe),Qe=function(a){Pe.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Qe(document);else{var Re=function(){Qe(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Re):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Re();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Re()})}Ne=function(){Oe(Pe.takeRecords())}}
var Se=Ne;var Te={};var Ue=Promise.resolve();function Ve(a){if(a=Te[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function We(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Xe(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,Ue.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))};var Ye=new Me;function Y(){this.B={};this.c=document.documentElement;var a=new Zc;a.rules=[];this.j=se(this.c,new re(a));this.o=!1;this.b=this.a=null}p=Y.prototype;p.flush=function(){Se()};p.Aa=function(a){return yd(a)};p.Ka=function(a){return R(a)};p.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
p.prepareTemplateStyles=function(a,b,c){if(!a.o){P||Je[b]||(Je[b]=Cd(b));a.o=!0;a.name=b;a.extends=c;Te[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),g=0;g<f.length;g++){var h=f[g];if(h.hasAttribute("shady-unscoped")){if(!P){var k=h.textContent;xd.has(k)||(xd.add(k),k=h.cloneNode(!0),document.head.appendChild(k));h.parentNode.removeChild(h)}}else e.push(h.textContent),h.parentNode.removeChild(h)}e=e.join("").trim();
c={is:b,extends:c,Oa:d};Ze(this);f=sd.test(e)||rd.test(e);sd.lastIndex=0;rd.lastIndex=0;e=$c(e);f&&Q&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.B=d;d=[];Q||(d=we(a._styleAst));if(!d.length||Q)e=P?a.content:null,b=Je[b]||null,f=Rd(c,a._styleAst),b=f.length?Ad(f,c.is,e,b):void 0,a.a=b;a.j=d}};p.prepareTemplateDom=function(a,b){P||a.c||(a.c=!0,Ld(a.content,b))};
function $e(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.ka(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.o)&&a.flushCustomStyles()})})}function Ze(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Ve);$e(a)}
p.flushCustomStyles=function(){Ze(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(Q)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&Q&&this.a){var d=yd(c);Ze(this);this.a.transformRules(d);c.textContent=R(d)}}else for(af(this,this.c,this.j),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&He(c,this.j.A);this.b.enqueued=!1;this.o&&!Q&&this.styleDocument()}}};
p.styleElement=function(a,b){var c=U(a).is,d=X(a);if(!d){var e=U(a);d=e.is;e=e.H;var f=Je[d]||null;d=Te[d];if(d){var g=d._styleAst;var h=d.j}g=new re(g,f,h,e);d&&se(a,g);d=g}a!==this.c&&(this.o=!0);b&&(d.D=d.D||{},Object.assign(d.D,b));if(Q){if(d.D){b=d.D;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=Te[c])||a===this.c)&&k&&k.a&&!We(k)){if(We(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)Ze(this),this.a&&this.a.transformRules(k._styleAst,c),k.a.textContent=
Rd(a,d.v),Xe(k);P&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=Rd(a,d.v));d.v=k._styleAst}}else if(this.flush(),af(this,a,d),d.Z&&d.Z.length){c=d;k=U(a).is;d=(b=Ye.fetch(k,c.A,c.Z))?b.styleElement:null;g=c.m;(h=b&&b.m)||(h=this.B[k]=(this.B[k]||0)+1,h=k+"-"+h);c.m=h;h=c.m;e=Ie;e=d?d.textContent||"":Ee(e,a,c.A,h);f=X(a);var l=f.a;l&&!P&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));P?f.a?(f.a.textContent=e,d=f.a):e&&(d=Ad(e,h,a.shadowRoot,f.b)):d?d.parentNode||
(ue&&-1<e.indexOf("@media")&&(d.textContent=e),Bd(d,null,f.b)):e&&(d=Ad(e,h,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);h=d;P||(d=c.m,f=e=a.getAttribute("class")||"",g&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&Id(a,f));b||Ye.store(k,c.A,h,c.m)}};function bf(a,b){return(b=b.getRootNode().host)?X(b)?b:bf(a,b):a.c}
function af(a,b,c){a=bf(a,b);var d=X(a);a=Object.create(d.A||null);var e=De(b,c.v);b=Be(d.v,b).u;Object.assign(a,e.Ca,b,e.Ia);b=c.D;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Ie;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=ze(f,a[d],a);c.A=a}p.styleDocument=function(a){this.styleSubtree(this.c,a)};
p.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};p.ka=function(a){var b=this,c=yd(a);S(c,function(a){if(P)oe(a);else{var c=W;a.selector=a.parsedSelector;oe(a);a.selector=a.i=Vd(c,a,c.c,void 0,void 0)}Q&&(Ze(b),b.a&&b.a.transformRule(a))});Q?a.textContent=R(c):this.j.v.rules.push(c)};
p.getComputedStyleValue=function(a,b){var c;Q||(c=(X(a)||X(bf(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};p.Ja=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===W.a){c=d[e+1];break}}}c&&b.push(W.a,c);Q||(c=X(a))&&c.m&&b.push(Ie.a,c.m);Id(a,b.join(" "))};p.wa=function(a){return X(a)};Y.prototype.flush=Y.prototype.flush;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Ja;Y.prototype._styleInfoForNode=Y.prototype.wa;Y.prototype.transformCustomStyleForDocument=Y.prototype.ka;Y.prototype.getStyleAst=Y.prototype.Aa;Y.prototype.styleAstToString=Y.prototype.Ka;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return P}},nativeCss:{get:function(){return Q}}});var Z=new Y,cf,df;window.ShadyCSS&&(cf=window.ShadyCSS.ApplyShim,df=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:Q,nativeShadow:P};cf&&(window.ShadyCSS.ApplyShim=cf);df&&(window.ShadyCSS.CustomStyleInterface=df);/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var ef=window.customElements,ff=window.HTMLImports,gf=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(ef&&ef.polyfillWrapFlushCallback){var hf,jf=function(){if(hf){gf.xa&&gf.xa(window.document);var a=hf;hf=null;a();return!0}},kf=ff.whenReady;ef.polyfillWrapFlushCallback(function(a){hf=a;kf(jf)});ff.whenReady=function(a){kf(function(){jf()?ff.whenReady(a):a()})}}
ff.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var lf=document.createElement("style");lf.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var mf=document.querySelector("head");mf.insertBefore(lf,mf.firstChild);/*

Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-sd.js.map
