(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(){function U(b){function a(e,a){Object.defineProperty(e,"innerHTML",{enumerable:a.enumerable,configurable:!0,get:a.get,set:function(e){var f=this,d=void 0;h(this)&&(d=[],q(this,function(b){b!==f&&d.push(b)}));a.set.call(this,e);if(d)for(var c=0;c<d.length;c++){var g=d[c];1===g.__CE_state&&b.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?b.f(this):b.l(this);return e}})}function d(e,a){l(e,"insertAdjacentElement",function(e,f){var d=h(f);e=a.call(this,e,f);d&&b.a(f);
h(e)&&b.b(f);return e})}E?l(Element.prototype,"attachShadow",function(b){return this.__CE_shadowRoot=b=E.call(this,b)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(v&&v.get)a(Element.prototype,v);else if(w&&w.get)a(HTMLElement.prototype,w);else{var c=x.call(document,"div");b.u(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return F.call(this,!0).innerHTML},set:function(b){var a="template"===this.localName?this.content:this;for(c.innerHTML=b;0<a.childNodes.length;)y.call(a,
a.childNodes[0]);for(;0<c.childNodes.length;)t.call(a,c.childNodes[0])}})})}l(Element.prototype,"setAttribute",function(a,f){if(1!==this.__CE_state)return G.call(this,a,f);var e=z.call(this,a);G.call(this,a,f);f=z.call(this,a);b.attributeChangedCallback(this,a,e,f,null)});l(Element.prototype,"setAttributeNS",function(a,f,d){if(1!==this.__CE_state)return H.call(this,a,f,d);var e=u.call(this,a,f);H.call(this,a,f,d);d=u.call(this,a,f);b.attributeChangedCallback(this,f,e,d,a)});l(Element.prototype,"removeAttribute",
function(a){if(1!==this.__CE_state)return I.call(this,a);var e=z.call(this,a);I.call(this,a);null!==e&&b.attributeChangedCallback(this,a,e,null,null)});l(Element.prototype,"removeAttributeNS",function(a,d){if(1!==this.__CE_state)return J.call(this,a,d);var e=u.call(this,a,d);J.call(this,a,d);var f=u.call(this,a,d);e!==f&&b.attributeChangedCallback(this,d,e,f,a)});K?d(HTMLElement.prototype,K):L?d(Element.prototype,L):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");
M(b,Element.prototype,{s:V,append:W});X(b,{A:Y,w:Z,replaceWith:aa,remove:ba})}function X(b,a){var d=Element.prototype;d.before=function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];f=e.filter(function(b){return b instanceof Node&&h(b)});a.A.apply(this,e);for(var c=0;c<f.length;c++)b.a(f[c]);if(h(this))for(f=0;f<e.length;f++)c=e[f],c instanceof Element&&b.b(c)};d.after=function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];f=e.filter(function(b){return b instanceof
Node&&h(b)});a.w.apply(this,e);for(var c=0;c<f.length;c++)b.a(f[c]);if(h(this))for(f=0;f<e.length;f++)c=e[f],c instanceof Element&&b.b(c)};d.replaceWith=function(d){for(var e=[],c=0;c<arguments.length;++c)e[c-0]=arguments[c];c=e.filter(function(b){return b instanceof Node&&h(b)});var g=h(this);a.replaceWith.apply(this,e);for(var p=0;p<c.length;p++)b.a(c[p]);if(g)for(b.a(this),c=0;c<e.length;c++)g=e[c],g instanceof Element&&b.b(g)};d.remove=function(){var d=h(this);a.remove.call(this);d&&b.a(this)}}
function ca(b){function a(a,c){Object.defineProperty(a,"textContent",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)c.set.call(this,a);else{var d=void 0;if(this.firstChild){var e=this.childNodes,p=e.length;if(0<p&&h(this)){d=Array(p);for(var r=0;r<p;r++)d[r]=e[r]}}c.set.call(this,a);if(d)for(a=0;a<d.length;a++)b.a(d[a])}}})}l(Node.prototype,"insertBefore",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);
a=N.call(this,a,c);if(h(this))for(c=0;c<d.length;c++)b.b(d[c]);return a}d=h(a);c=N.call(this,a,c);d&&b.a(a);h(this)&&b.b(a);return c});l(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=t.call(this,a);if(h(this))for(var d=0;d<c.length;d++)b.b(c[d]);return a}c=h(a);d=t.call(this,a);c&&b.a(a);h(this)&&b.b(a);return d});l(Node.prototype,"cloneNode",function(a){a=F.call(this,a);this.ownerDocument.__CE_hasRegistry?b.f(a):b.l(a);
return a});l(Node.prototype,"removeChild",function(a){var c=h(a),d=y.call(this,a);c&&b.a(a);return d});l(Node.prototype,"replaceChild",function(a,c){if(a instanceof DocumentFragment){var e=Array.prototype.slice.apply(a.childNodes);a=O.call(this,a,c);if(h(this))for(b.a(c),c=0;c<e.length;c++)b.b(e[c]);return a}e=h(a);var d=O.call(this,a,c),g=h(this);g&&b.a(c);e&&b.a(a);g&&b.b(a);return d});A&&A.get?a(Node.prototype,A):b.u(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=
0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)y.call(this,this.firstChild);t.call(this,document.createTextNode(a))}})})}function da(b){l(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var d=b.c(a);if(d)return new d.constructor}a=x.call(this,a);b.g(a);return a});l(Document.prototype,"importNode",function(a,d){a=ea.call(this,a,d);this.__CE_hasRegistry?b.f(a):b.l(a);return a});l(Document.prototype,
"createElementNS",function(a,d){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var c=b.c(d);if(c)return new c.constructor}a=fa.call(this,a,d);b.g(a);return a});M(b,Document.prototype,{s:ha,append:ia})}function M(b,a,d){a.prepend=function(a){for(var c=[],f=0;f<arguments.length;++f)c[f-0]=arguments[f];f=c.filter(function(a){return a instanceof Node&&h(a)});d.s.apply(this,c);for(var g=0;g<f.length;g++)b.a(f[g]);if(h(this))for(f=0;f<c.length;f++)g=c[f],g instanceof Element&&
b.b(g)};a.append=function(a){for(var c=[],f=0;f<arguments.length;++f)c[f-0]=arguments[f];f=c.filter(function(a){return a instanceof Node&&h(a)});d.append.apply(this,c);for(var g=0;g<f.length;g++)b.a(f[g]);if(h(this))for(f=0;f<c.length;f++)g=c[f],g instanceof Element&&b.b(g)}}function ja(b){window.HTMLElement=function(){function a(){var a=this.constructor,c=b.B(a);if(!c)throw Error("The custom element being constructed was not registered with `customElements`.");var e=c.constructionStack;if(0===e.length)return e=
x.call(document,c.localName),Object.setPrototypeOf(e,a.prototype),e.__CE_state=1,e.__CE_definition=c,b.g(e),e;c=e.length-1;var f=e[c];if(f===P)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");e[c]=P;Object.setPrototypeOf(f,a.prototype);b.g(f);return f}a.prototype=ka.prototype;return a}()}function k(b){this.c=!1;this.a=b;this.h=new Map;this.f=function(a){return a()};this.b=!1;this.g=[];this.i=new B(b,document)}function Q(){var b=
this;this.b=this.a=void 0;this.f=new Promise(function(a){b.b=a;b.a&&a(b.a)})}function B(b,a){this.c=b;this.a=a;this.b=void 0;this.c.f(this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.g.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function m(){this.o=new Map;this.m=new Map;this.j=[];this.h=!1}function R(b){var a=la.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function h(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||
b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}function C(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}function q(b,a,d){d=d?d:new Set;for(var c=b;c;){if(c.nodeType===Node.ELEMENT_NODE){var e=c;a(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){c=e.import;if(c instanceof Node&&!d.has(c))for(d.add(c),c=c.firstChild;c;c=c.nextSibling)q(c,
a,d);c=C(b,e);continue}else if("template"===f){c=C(b,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)q(e,a,d)}c=c.firstChild?c.firstChild:C(b,c)}}function l(b,a,d){b[a]=d}function S(){requestAnimationFrame(function(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})}function T(){S();D.removeEventListener("readystatechange",T)}var la=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));
m.prototype.C=function(b,a){this.o.set(b,a);this.m.set(a.constructor,a)};m.prototype.c=function(b){return this.o.get(b)};m.prototype.B=function(b){return this.m.get(b)};m.prototype.u=function(b){this.h=!0;this.j.push(b)};m.prototype.l=function(b){var a=this;this.h&&q(b,function(b){return a.g(b)})};m.prototype.g=function(b){if(this.h&&!b.__CE_patched){b.__CE_patched=!0;for(var a=0;a<this.j.length;a++)this.j[a](b)}};m.prototype.b=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=
a[b];1===d.__CE_state?this.connectedCallback(d):this.i(d)}};m.prototype.a=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state&&this.disconnectedCallback(d)}};m.prototype.f=function(b,a){var d=this;a=a?a:{};var c=a.D||new Set,e=a.v||function(a){return d.i(a)},f=[];q(b,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var b=a.import;b instanceof Node&&"complete"===b.readyState?(b.__CE_isImportDocument=!0,b.__CE_hasRegistry=
!0):a.addEventListener("load",function(){var b=a.import;b.__CE_documentLoadHandled||(b.__CE_documentLoadHandled=!0,b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0,c.delete(b),d.f(b,{D:c,v:e}))})}else f.push(a)},c);if(this.h)for(b=0;b<f.length;b++)this.g(f[b]);for(b=0;b<f.length;b++)e(f[b])};m.prototype.i=function(b){if(void 0===b.__CE_state){var a=this.c(b.localName);if(a){a.constructionStack.push(b);var d=a.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");
}finally{a.constructionStack.pop()}}catch(f){throw b.__CE_state=2,f;}b.__CE_state=1;b.__CE_definition=a;if(a.attributeChangedCallback)for(a=a.observedAttributes,d=0;d<a.length;d++){var c=a[d],e=b.getAttribute(c);null!==e&&this.attributeChangedCallback(b,c,null,e,null)}h(b)&&this.connectedCallback(b)}}};m.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};m.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&
a.disconnectedCallback.call(b)};m.prototype.attributeChangedCallback=function(b,a,d,c,e){var f=b.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(a)&&f.attributeChangedCallback.call(b,a,d,c,e)};B.prototype.f=function(){this.b&&this.b.disconnect()};B.prototype.g=function(b){var a=this.a.readyState;"interactive"!==a&&"complete"!==a||this.f();for(a=0;a<b.length;a++)for(var d=b[a].addedNodes,c=0;c<d.length;c++)this.c.f(d[c])};Q.prototype.c=function(){if(this.a)throw Error("Already resolved.");
this.a=void 0;this.b&&this.b(void 0)};k.prototype.define=function(b,a){var d=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!R(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.a.c(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var c=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+
a+"' callback must be a function.");return b},e=a.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=c("connectedCallback");var g=c("disconnectedCallback");var h=c("adoptedCallback");var k=c("attributeChangedCallback");var l=a.observedAttributes||[]}catch(ma){return}finally{this.c=!1}a={localName:b,constructor:a,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};
this.a.C(b,a);this.g.push(a);this.b||(this.b=!0,this.f(function(){return d.j()}))};k.prototype.j=function(){var b=this;if(!1!==this.b){this.b=!1;for(var a=this.g,d=[],c=new Map,e=0;e<a.length;e++)c.set(a[e].localName,[]);this.a.f(document,{v:function(a){if(void 0===a.__CE_state){var e=a.localName,f=c.get(e);f?f.push(a):b.a.c(e)&&d.push(a)}}});for(e=0;e<d.length;e++)this.a.i(d[e]);for(;0<a.length;){var f=a.shift();e=f.localName;f=c.get(f.localName);for(var g=0;g<f.length;g++)this.a.i(f[g]);(e=this.h.get(e))&&
e.c()}}};k.prototype.get=function(b){if(b=this.a.c(b))return b.constructor};k.prototype.whenDefined=function(b){if(!R(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.h.get(b);if(a)return a.f;a=new Q;this.h.set(b,a);this.a.c(b)&&!this.g.some(function(a){return a.localName===b})&&a.c();return a.f};k.prototype.l=function(b){this.i.f();var a=this.f;this.f=function(d){return b(function(){return a(d)})}};window.CustomElementRegistry=k;k.prototype.define=
k.prototype.define;k.prototype.get=k.prototype.get;k.prototype.whenDefined=k.prototype.whenDefined;k.prototype.polyfillWrapFlushCallback=k.prototype.l;var x=window.Document.prototype.createElement,fa=window.Document.prototype.createElementNS,ea=window.Document.prototype.importNode,ha=window.Document.prototype.prepend,ia=window.Document.prototype.append,F=window.Node.prototype.cloneNode,t=window.Node.prototype.appendChild,N=window.Node.prototype.insertBefore,y=window.Node.prototype.removeChild,O=window.Node.prototype.replaceChild,
A=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),E=window.Element.prototype.attachShadow,v=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),z=window.Element.prototype.getAttribute,G=window.Element.prototype.setAttribute,I=window.Element.prototype.removeAttribute,u=window.Element.prototype.getAttributeNS,H=window.Element.prototype.setAttributeNS,J=window.Element.prototype.removeAttributeNS,L=window.Element.prototype.insertAdjacentElement,V=window.Element.prototype.prepend,
W=window.Element.prototype.append,Y=window.Element.prototype.before,Z=window.Element.prototype.after,aa=window.Element.prototype.replaceWith,ba=window.Element.prototype.remove,ka=window.HTMLElement,w=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),K=window.HTMLElement.prototype.insertAdjacentElement,P=new function(){},n=window.customElements;if(!n||n.forcePolyfill||"function"!=typeof n.define||"function"!=typeof n.get)n=new m,ja(n),da(n),ca(n),U(n),document.__CE_hasRegistry=
!0,n=new k(n),Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:n});var D=window.document;window.WebComponents=window.WebComponents||{};"loading"!==D.readyState?S():D.addEventListener("readystatechange",T)})();}).call(this);

//# sourceMappingURL=webcomponents-ce.js.map
