/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var m,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};q.Symbol||(q.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function da(){ba();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(this)}});da=function(){}}function ea(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){da();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ha(a){da();ba();da();var b=a[Symbol.iterator];return b?b.call(a):ea(a)}
function ia(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ja(){this.ea=this.root=null;this.N=!1;this.v=this.J=this.U=this.assignedSlot=this.assignedNodes=this.A=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.D=void 0;this.ia=this.aa=!1;this.I={}}ja.prototype.toJSON=function(){return{}};function r(a){a.S||(a.S=new ja);return a.S}function t(a){return a&&a.S};var u=window.ShadyDOM||{};u.ta=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ka=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");u.m=!!(ka&&ka.configurable&&ka.get);u.W=u.force||!u.ta;var la=navigator.userAgent.match("Trident"),ma=navigator.userAgent.match("Edge");void 0===u.ga&&(u.ga=u.m&&(la||ma));function v(a){return(a=t(a))&&void 0!==a.firstChild}function w(a){return"ShadyRoot"===a.na}function x(a){a=a.getRootNode();if(w(a))return a}
var y=Element.prototype,na=y.matches||y.matchesSelector||y.mozMatchesSelector||y.msMatchesSelector||y.oMatchesSelector||y.webkitMatchesSelector;function oa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function qa(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)oa(a,c[d]);return a}function ra(a,b){for(var c in b)a[c]=b[c]}
var sa=document.createTextNode(""),ta=0,ua=[];(new MutationObserver(function(){for(;ua.length;)try{ua.shift()()}catch(a){throw sa.textContent=ta++,a;}})).observe(sa,{characterData:!0});function va(a){ua.push(a);sa.textContent=ta++}var wa=!!document.contains;function xa(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function ya(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ha(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var za=[],Aa;function Ba(a){Aa||(Aa=!0,va(Ca));za.push(a)}function Ca(){Aa=!1;for(var a=!!za.length;za.length;)za.shift()();return a}Ca.list=za;function Da(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.M=new Set}function Ea(a){a.a||(a.a=!0,va(function(){Fa(a)}))}function Fa(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.M.forEach(function(a){a(b)})}}Da.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ga(a,b){var c=r(a);c.A||(c.A=new Da);c.A.M.add(b);var d=c.A;return{ma:b,pa:d,oa:a,takeRecords:function(){return d.takeRecords()}}}function Ha(a){var b=a&&a.pa;b&&(b.M.delete(a.ma),b.M.size||(r(a.oa).A=null))}
function Ia(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var z={},Ja=Element.prototype.insertBefore,Ka=Element.prototype.replaceChild,La=Element.prototype.removeChild,Ma=Element.prototype.setAttribute,Na=Element.prototype.removeAttribute,Oa=Element.prototype.cloneNode,Pa=Document.prototype.importNode,Qa=Element.prototype.addEventListener,Ra=Element.prototype.removeEventListener,Sa=Window.prototype.addEventListener,Ta=Window.prototype.removeEventListener,Ua=Element.prototype.dispatchEvent,Va=Node.prototype.contains||HTMLElement.prototype.contains,Wa=Document.prototype.getElementById,
Xa=Element.prototype.querySelector,Ya=DocumentFragment.prototype.querySelector,Za=Document.prototype.querySelector,$a=Element.prototype.querySelectorAll,ab=DocumentFragment.prototype.querySelectorAll,bb=Document.prototype.querySelectorAll;z.appendChild=Element.prototype.appendChild;z.insertBefore=Ja;z.replaceChild=Ka;z.removeChild=La;z.setAttribute=Ma;z.removeAttribute=Na;z.cloneNode=Oa;z.importNode=Pa;z.addEventListener=Qa;z.removeEventListener=Ra;z.za=Sa;z.Aa=Ta;z.dispatchEvent=Ua;z.contains=Va;
z.getElementById=Wa;z.Ia=Xa;z.La=Ya;z.Ga=Za;z.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Xa.call(this,a);case Node.DOCUMENT_NODE:return Za.call(this,a);default:return Ya.call(this,a)}};z.Ja=$a;z.Ma=ab;z.Ha=bb;z.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return $a.call(this,a);case Node.DOCUMENT_NODE:return bb.call(this,a);default:return ab.call(this,a)}};var cb=/[&\u00A0"]/g,db=/[&\u00A0<>]/g;function eb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function fb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var gb=fb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),hb=fb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function ib(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var n=h.localName,p="<"+n,K=h.attributes,J=0;k=K[J];J++)p+=" "+k.name+'="'+k.value.replace(cb,eb)+'"';p+=">";h=gb[n]?p:p+ib(h,l)+"</"+n+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&hb[k.localName]?h:h.replace(db,eb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var A={},B=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),C=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function jb(a){var b=[];B.currentNode=a;for(a=B.firstChild();a;)b.push(a),a=B.nextSibling();return b}A.parentNode=function(a){B.currentNode=a;return B.parentNode()};A.firstChild=function(a){B.currentNode=a;return B.firstChild()};A.lastChild=function(a){B.currentNode=a;return B.lastChild()};A.previousSibling=function(a){B.currentNode=a;return B.previousSibling()};
A.nextSibling=function(a){B.currentNode=a;return B.nextSibling()};A.childNodes=jb;A.parentElement=function(a){C.currentNode=a;return C.parentNode()};A.firstElementChild=function(a){C.currentNode=a;return C.firstChild()};A.lastElementChild=function(a){C.currentNode=a;return C.lastChild()};A.previousElementSibling=function(a){C.currentNode=a;return C.previousSibling()};A.nextElementSibling=function(a){C.currentNode=a;return C.nextSibling()};
A.children=function(a){var b=[];C.currentNode=a;for(a=C.firstChild();a;)b.push(a),a=C.nextSibling();return ya(b)};A.innerHTML=function(a){return ib(a,function(a){return jb(a)})};A.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var D={},kb=u.m,lb=[Node.prototype,Element.prototype,HTMLElement.prototype];function E(a){var b;a:{for(b=0;b<lb.length;b++){var c=lb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var F=kb?{parentNode:E("parentNode"),firstChild:E("firstChild"),lastChild:E("lastChild"),previousSibling:E("previousSibling"),nextSibling:E("nextSibling"),childNodes:E("childNodes"),parentElement:E("parentElement"),previousElementSibling:E("previousElementSibling"),nextElementSibling:E("nextElementSibling"),innerHTML:E("innerHTML"),textContent:E("textContent"),firstElementChild:E("firstElementChild"),lastElementChild:E("lastElementChild"),children:E("children")}:{},mb=kb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},nb=kb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{};D.da=F;D.Ka=mb;D.Fa=nb;D.parentNode=function(a){return F.parentNode.get.call(a)};
D.firstChild=function(a){return F.firstChild.get.call(a)};D.lastChild=function(a){return F.lastChild.get.call(a)};D.previousSibling=function(a){return F.previousSibling.get.call(a)};D.nextSibling=function(a){return F.nextSibling.get.call(a)};D.childNodes=function(a){return Array.prototype.slice.call(F.childNodes.get.call(a))};D.parentElement=function(a){return F.parentElement.get.call(a)};D.previousElementSibling=function(a){return F.previousElementSibling.get.call(a)};D.nextElementSibling=function(a){return F.nextElementSibling.get.call(a)};
D.innerHTML=function(a){return F.innerHTML.get.call(a)};D.textContent=function(a){return F.textContent.get.call(a)};D.children=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return mb.children.get.call(a);case Node.DOCUMENT_NODE:return nb.children.get.call(a);default:return F.children.get.call(a)}};
D.firstElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return mb.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return nb.firstElementChild.get.call(a);default:return F.firstElementChild.get.call(a)}};D.lastElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return mb.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return nb.lastElementChild.get.call(a);default:return F.lastElementChild.get.call(a)}};var G=u.ga?D:A;function ob(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var pb=u.m,qb=document.implementation.createHTMLDocument("inert"),rb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),sb=rb&&rb.get,tb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),ub={parentElement:{get:function(){var a=t(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:G.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=t(this);a=a&&a.parentNode;return void 0!==a?a:G.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=t(this);a=a&&a.nextSibling;return void 0!==a?a:G.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=t(this);a=a&&a.previousSibling;return void 0!==a?a:G.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=t(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return G.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
t(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return G.previousElementSibling(this)},configurable:!0}},vb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},wb={childNodes:{get:function(){if(v(this)){var a=t(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
G.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=t(this);a=a&&a.firstChild;return void 0!==a?a:G.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=t(this);a=a&&a.lastChild;return void 0!==a?a:G.lastChild(this)},configurable:!0},textContent:{get:function(){if(v(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return G.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!v(this)&&pb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&ob(this);D.da.textContent.set.call(this,a)}else ob(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
t(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return G.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=t(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return G.lastElementChild(this)},configurable:!0},children:{get:function(){return v(this)?ya(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
G.children(this)},configurable:!0},innerHTML:{get:function(){return v(this)?ib("template"===this.localName?this.content:this):G.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;ob(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==qb.namespaceURI?qb.createElementNS(this.namespaceURI,c):qb.createElement(c);pb?D.da.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
xb={shadowRoot:{get:function(){var a=t(this);return a&&a.ea||null},configurable:!0}},yb={activeElement:{get:function(){var a=tb&&tb.get?tb.get.call(document):u.m?void 0:document.activeElement;if(a&&a.nodeType){var b=!!w(this);if(this===document||b&&this.host!==a&&z.contains.call(this.host,a)){for(b=x(a);b&&b!==this;)a=b.host,b=x(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function H(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function I(a){H(a,ub);H(a,vb);H(a,wb);H(a,yb)}
function zb(){var a=Ab.prototype;a.__proto__=DocumentFragment.prototype;H(a,ub,!0);H(a,wb,!0);H(a,yb,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Bb=u.m?function(){}:function(a){var b=r(a);b.aa||(b.aa=!0,H(a,ub,!0),H(a,vb,!0))},Cb=u.m?function(){}:function(a){r(a).ia||(H(a,wb,!0),H(a,xb,!0))};var Db=G.childNodes;function Eb(a,b,c){Bb(a);c=c||null;var d=r(a),e=r(b),f=c?r(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=t(d.previousSibling))f.nextSibling=a;if(f=t(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Fb(a){var b=r(a);if(void 0===b.firstChild){b.childNodes=null;var c=Db(a);b.firstChild=c[0]||null;b.lastChild=c[c.length-1]||null;Cb(a);for(b=0;b<c.length;b++){var d=c[b],e=r(d);e.parentNode=a;e.nextSibling=c[b+1]||null;e.previousSibling=c[b-1]||null;Bb(d)}}};var Gb=G.parentNode;
function Hb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=t(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Gb(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Ib(b.parentNode,b);d=!0;var e,f;if(!b.__noInsertionPoint){if(f=e=x(a)){var g;"slot"===b.localName?g=[b]:b.querySelectorAll&&
(g=b.querySelectorAll("slot"));f=g&&g.length?g:void 0}if(f){g=e;var h=f;g.a=g.a||[];g.f=g.f||[];g.g=g.g||{};g.a.push.apply(g.a,[].concat(h instanceof Array?h:ia(ha(h))))}}("slot"===a.localName||f)&&(e=e||x(a))&&L(e);if(v(a)){e=c;Cb(a);f=r(a);void 0!==f.firstChild&&(f.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(g=0;g<f.length;g++)Eb(f[g],a,e);e=r(b);f=void 0!==e.firstChild?null:void 0;e.firstChild=e.lastChild=f;e.childNodes=f}else Eb(b,a,e);e=t(a);Jb(a)?(L(e.root),
d=!1):e.root&&(d=!1)}d?(d=w(a)?a.host:a,c?(c=Kb(c),z.insertBefore.call(d,b,c)):z.appendChild.call(d,b)):b.ownerDocument!==a.ownerDocument&&a.ownerDocument.adoptNode(b);Lb(a,b);return b}
function Ib(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=x(b),d=t(a);if(v(a)){var e=r(b),f=r(a);b===f.firstChild&&(f.firstChild=e.nextSibling);b===f.lastChild&&(f.lastChild=e.previousSibling);var g=e.previousSibling,h=e.nextSibling;g&&(r(g).nextSibling=h);h&&(r(h).previousSibling=g);e.parentNode=e.previousSibling=e.nextSibling=void 0;void 0!==f.childNodes&&(f.childNodes=null);if(Jb(a)){L(d.root);var k=!0}}Mb(b);if(c){(e=a&&"slot"===a.localName)&&
(k=!0);if(c.f){Nb(c);f=c.g;for(pa in f)for(g=f[pa],h=0;h<g.length;h++){var l=g[h];if(xa(b,l)){g.splice(h,1);var n=c.f.indexOf(l);0<=n&&c.f.splice(n,1);h--;n=t(l);if(l=n.v)for(var p=0;p<l.length;p++){var K=l[p],J=Ob(K);J&&z.removeChild.call(J,K)}n.v=[];n.assignedNodes=[];n=!0}}var pa=n}else pa=void 0;(pa||e)&&L(c)}k||(k=w(a)?a.host:a,(!d.root&&"slot"!==b.localName||k===Gb(b))&&z.removeChild.call(k,b));Lb(a,null,b);return b}
function Mb(a){var b=t(a);if(b&&void 0!==b.D){b=a.childNodes;for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)Mb(e)}if(a=t(a))a.D=void 0}function Kb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=t(a))&&b.v)&&b.length?b[0]:Kb(a.nextSibling));return b}function Jb(a){return(a=(a=t(a))&&a.root)&&Pb(a)}
function Qb(a,b){if("slot"===b)a=a.parentNode,Jb(a)&&L(t(a).root);else if("slot"===a.localName&&"name"===b&&(b=x(a))){if(b.f){Nb(b);var c=a.la,d=Rb(a);if(d!==c){c=b.g[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.g[d]||(b.g[d]=[]);c.push(a);1<c.length&&(b.g[d]=Sb(c))}}L(b)}}function Lb(a,b,c){if(a=(a=t(a))&&a.A)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ea(a)}
function Tb(a){if(a&&a.nodeType){var b=r(a),c=b.D;void 0===c&&(w(a)?(c=a,b.D=c):(c=(c=a.parentNode)?Tb(c):a,z.contains.call(document.documentElement,a)&&(b.D=c)));return c}}function Ub(a,b,c){var d=[];Vb(a.childNodes,b,c,d);return d}function Vb(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,n=d,p=k(h);p&&n.push(h);l&&l(p)?h=p:(Vb(h.childNodes,k,l,n),h=void 0)}if(h)break}}var Wb=null;
function Xb(a,b,c){Wb||(Wb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);Wb&&"class"===b?Wb.setElementClass(a,c):(z.setAttribute.call(a,b,c),Qb(a,b))}function Yb(a,b){if(a.ownerDocument!==document||"template"===a.localName)return z.importNode.call(document,a,b);var c=z.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Yb(a[b],!0),c.appendChild(d)}return c};var Zb="__eventWrappers"+Date.now(),$b=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),ac={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},bc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function cc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function dc(a,b){if(!w)return a;a=cc(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!w(f)||-1<g)return d}
var ec={get composed(){void 0===this.H&&($b?this.H=$b(this):!1!==this.isTrusted&&(this.H=ac[this.type]));return this.H||!1},composedPath:function(){this.$||(this.$=cc(this.__target,this.composed));return this.$},get target(){return dc(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.R)return null;this.ba||(this.ba=cc(this.R,!0));return dc(this.currentTarget||this.__previousCurrentTarget,this.ba)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);
this.P=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.P=this.ha=!0}};function fc(a){function b(b,d){b=new a(b,d);b.H=d&&!!d.composed;return b}ra(b,a);b.prototype=a.prototype;return b}var gc={focus:!0,blur:!0};function hc(a){return a.__target!==a.target||a.R!==a.relatedTarget}function ic(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!hc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.ha);d++);}
function jc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];ic(a,d,"capture");if(a.P)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=t(d);f=f&&f.root;if(0===c||f&&f===e)if(ic(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.P)break}}
function kc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,n=h.once,p=h.passive;if(b===h.node&&c===k&&d===l&&e===n&&f===p)return g}return-1}
function lc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?z.za:z.addEventListener;if(bc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.T||this,l=b[Zb];if(l){if(-1<kc(l,k,a,f,g,h))return}else b[Zb]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||mc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}e.__previousCurrentTarget=e.currentTarget;if(!w(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(hc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&
(f?(Object.defineProperty(e,"currentTarget",f),f=null):delete e.currentTarget);return h}};b[Zb].push({node:k,type:a,capture:f,once:g,passive:h,Ba:l});gc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function nc(a,b,c){if(b){var d=this instanceof Window?z.Aa:z.removeEventListener;if(bc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.T||this,k=void 0;var l=null;try{l=b[Zb]}catch(n){}l&&(f=kc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Ba,l.length||(b[Zb]=void 0)));d.call(this,a,k||b,c);k&&gc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function oc(){for(var a in gc)window.addEventListener(a,function(a){a.__target||(mc(a),jc(a))},!0)}function mc(a){a.__target=a.target;a.R=a.relatedTarget;if(u.m){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Da=b;oa(c,ec);b.__patchProto=c}a.__proto__=b.__patchProto}else oa(a,ec)}var pc=fc(window.Event),qc=fc(window.CustomEvent),rc=fc(window.MouseEvent);
function sc(){window.Event=pc;window.CustomEvent=qc;window.MouseEvent=rc;oc();if(!$b&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function tc(a,b){return{index:a,F:[],L:b}}
function uc(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,n=0;n<k-g&&vc(a[--h],c[--l]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=tc(e,0);f<d;)b.F.push(c[f++]);return[b]}if(f==d)return[tc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+l-1])b[l][n]=
b[l-1][n-1];else{var p=b[l-1][n]+1,K=b[l][n-1]+1;b[l][n]=p<K?p:K}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],n=b[k][g-1],p=l<n?l<h?l:h:n<h?n:h,p==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):p==l?(a.push(3),k--,d=l):(a.push(2),g--,d=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=tc(e,0));b.L++;e++;b.F.push(c[f]);f++;break;case 2:b||(b=tc(e,0));
b.L++;e++;break;case 3:b||(b=tc(e,0)),b.F.push(c[f]),f++}b&&k.push(b);return k}function vc(a,b){return a===b};var Ob=G.parentNode,wc=G.childNodes,xc={},M=u.deferConnectionCallbacks&&"loading"===document.readyState,yc;function zc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function Ab(a,b,c){if(a!==xc)throw new TypeError("Illegal constructor");this.na="ShadyRoot";this.host=b;this.c=c&&c.mode;Fb(b);a=r(b);a.root=this;a.ea="closed"!==this.c?this:null;a=r(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.b=this.K=!1;this.a=this.g=this.f=null;L(this)}function L(a){a.K||(a.K=!0,Ba(function(){return Ac(a)}))}
function Ac(a){for(var b;a;){a.K&&(b=a);a:{var c=a;a=c.host.getRootNode();if(w(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
Ab.prototype._renderRoot=function(){var a=M;M=!0;this.K=!1;if(this.f){Nb(this);for(var b=0,c;b<this.f.length;b++){c=this.f[b];var d=t(c),e=d.assignedNodes;d.assignedNodes=[];d.v=[];if(d.U=e)for(d=0;d<e.length;d++){var f=t(e[d]);f.J=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(c=this.host.firstChild;c;c=c.nextSibling)Bc(this,c);for(b=0;b<this.f.length;b++){c=this.f[b];e=t(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Bc(this,d,c);(d=(d=t(c.parentNode))&&d.root)&&
Pb(d)&&d._renderRoot();Cc(this,e.v,e.assignedNodes);if(d=e.U){for(f=0;f<d.length;f++)t(d[f]).J=null;e.U=null;d.length>e.assignedNodes.length&&(e.N=!0)}e.N&&(e.N=!1,Dc(this,c))}b=this.f;c=[];for(e=0;e<b.length;e++)d=b[e].parentNode,(f=t(d))&&f.root||!(0>c.indexOf(d))||c.push(d);for(b=0;b<c.length;b++){e=c[b];d=e===this?this.host:e;f=[];e=e.childNodes;for(var g=0;g<e.length;g++){var h=e[g];if("slot"==h.localName){h=t(h).v;for(var k=0;k<h.length;k++)f.push(h[k])}else f.push(h)}e=void 0;g=wc(d);h=uc(f,
f.length,g,g.length);for(var l=k=0;k<h.length&&(e=h[k]);k++){for(var n=0,p;n<e.F.length&&(p=e.F[n]);n++)Ob(p)===d&&z.removeChild.call(d,p),g.splice(e.index+l,1);l-=e.L}for(l=0;l<h.length&&(e=h[l]);l++)for(k=g[e.index],n=e.index;n<e.index+e.L;n++)p=f[n],z.insertBefore.call(d,p,k),g.splice(n,0,p)}}if(!this.b)for(p=this.host.childNodes,c=0,b=p.length;c<b;c++)e=p[c],d=t(e),Ob(e)!==this.host||"slot"!==e.localName&&d.assignedSlot||z.removeChild.call(this.host,e);this.b=!0;M=a;yc&&yc()};
function Bc(a,b,c){var d=r(b),e=d.J;d.J=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(r(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(r(d.assignedSlot).N=!0)}function Cc(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=t(e).assignedNodes;f&&f.length&&Cc(a,b,f)}else b.push(c[d])}function Dc(a,b){z.dispatchEvent.call(b,new Event("slotchange"));b=t(b);b.assignedSlot&&Dc(a,b.assignedSlot)}
function Nb(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];Fb(e);Fb(e.parentNode);var f=Rb(e);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(e)):a.g[f]=[e];a.f.push(e)}if(c)for(var g in c)a.g[g]=Sb(a.g[g]);a.a=[]}}function Rb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.la=b}function Sb(a){return a.sort(function(a,c){a=zc(a);for(var b=zc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Pb(a){Nb(a);return!(!a.f||!a.f.length)}
if(window.customElements&&u.W){var Ec=new Map;yc=function(){var a=Array.from(Ec);Ec.clear();a=ha(a);for(var b=a.next();!b.done;b=a.next()){b=ha(b.value);var c=b.next().value;b.next().value?c.ja():c.ka()}};M&&document.addEventListener("readystatechange",function(){M=!1;yc()},{once:!0});var Fc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.ja=function(){M?Ec.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.ka=
function(){M?this.isConnected||Ec.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},define=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;define.call(window.customElements,a,Fc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Gc(a){var b=a.getRootNode();w(b)&&Ac(b);return(a=t(a))&&a.assignedSlot||null}
var Hc={addEventListener:lc.bind(window),removeEventListener:nc.bind(window)},Ic={addEventListener:lc,removeEventListener:nc,appendChild:function(a){return Hb(this,a)},insertBefore:function(a,b){return Hb(this,a,b)},removeChild:function(a){return Ib(this,a)},replaceChild:function(a,b){Hb(this,a,b);Ib(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=z.cloneNode.call(this,a);else if(b=z.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Tb(this)},contains:function(a){return xa(this,a)},dispatchEvent:function(a){Ca();return z.dispatchEvent.call(this,a)}};
Object.defineProperties(Ic,{isConnected:{get:function(){if(sb&&sb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(wa){if(z.contains.call(a,this))return!0}else if(a.documentElement&&z.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(w(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Jc={get assignedSlot(){return Gc(this)}},Kc={querySelector:function(a){return Ub(this,function(b){return na.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(z.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Ub(this,function(b){return na.call(b,a)})}},Lc={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();w(b)&&Ac(b);return(b=t(this))?
(a&&a.flatten?b.v:b.assignedNodes)||[]:[]}}},Mc=qa({setAttribute:function(a,b){Xb(this,a,b)},removeAttribute:function(a){z.removeAttribute.call(this,a);Qb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new Ab(xc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Xb(this,"slot",a)},get assignedSlot(){return Gc(this)}},Kc,Lc);Object.defineProperties(Mc,xb);
var Nc=qa({importNode:function(a,b){return Yb(a,b)},getElementById:function(a){return Ub(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Kc);Object.defineProperties(Nc,{_activeElement:yb.activeElement});
for(var Oc=HTMLElement.prototype.blur,Pc={blur:function(){var a=t(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Oc.call(this)}},N={},Qc=ha(Object.getOwnPropertyNames(Document.prototype)),Rc=Qc.next();!Rc.done;N={j:N.j},Rc=Qc.next())N.j=Rc.value,"on"===N.j.substring(0,2)&&Object.defineProperty(Pc,N.j,{set:function(a){return function(b){var c=r(this),d=a.j.substring(2);c.I[a.j]&&this.removeEventListener(d,c.I[a.j]);this.addEventListener(d,b,{});c.I[a.j]=b}}(N),get:function(a){return function(){var b=
t(this);return b&&b.I[a.j]}}(N),configurable:!0});var Sc={addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.T=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.T=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Ub(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};
function O(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(u.W){var ShadyDOM={inUse:u.W,patch:function(a){Cb(a);Bb(a);return a},isShadyRoot:w,enqueue:Ba,flush:Ca,settings:u,filterMutations:Ia,observeChildren:Ga,unobserveChildren:Ha,nativeMethods:z,nativeTree:G,deferConnectionCallbacks:u.deferConnectionCallbacks};window.ShadyDOM=ShadyDOM;sc();var Tc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;O(Ab.prototype,Sc);O(window.Node.prototype,Ic);O(window.Window.prototype,Hc);O(window.Text.prototype,Jc);O(window.DocumentFragment.prototype,
Kc);O(window.Element.prototype,Mc);O(window.Document.prototype,Nc);window.HTMLSlotElement&&O(window.HTMLSlotElement.prototype,Lc);O(Tc.prototype,Pc);u.m&&(I(window.Node.prototype),I(window.Text.prototype),I(window.DocumentFragment.prototype),I(window.Element.prototype),I(Tc.prototype),I(window.Document.prototype),window.HTMLSlotElement&&I(window.HTMLSlotElement.prototype));zb();window.ShadowRoot=Ab};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Uc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Vc(a){a=a.replace(Wc,"").replace(Xc,"");var b=Yc,c=a,d=new Uc;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new Uc;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function Yc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Zc(c),c=c.replace($c," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=ad:c.match(bd)&&(a.type=cd,a.keyframesName=a.selector.split($c).pop()):a.type=0===c.indexOf("--")?dd:ed);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)Yc(f,
b);return a}function Zc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function fd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=fd(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(gd,"").replace(hd,""),b=b.replace(id,"").replace(jd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var ed=1,cd=7,ad=4,dd=1E3,Wc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Xc=/@import[^;]*;/gim,gd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,hd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,id=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,jd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,bd=/^@[^\s]*keyframes/,$c=/\s+/g;var P=!(window.ShadyDOM&&window.ShadyDOM.inUse),kd;function ld(a){kd=a&&a.shimcssproperties?!1:P||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?kd=window.ShadyCSS.nativeCss:window.ShadyCSS?(ld(window.ShadyCSS),window.ShadyCSS=void 0):ld(window.WebComponents&&window.WebComponents.flags);var Q=kd;var md=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,nd=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,od=/(--[\w-]+)\s*([:,;)]|$)/gi,pd=/(animation\s*:)|(animation-name\s*:)/,qd=/@media\s(.*)/,rd=/\{[^}]*\}/g;var sd=new Set;function R(a,b){if(!a)return"";"string"===typeof a&&(a=Vc(a));b&&S(a,b);return fd(a,Q)}function td(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Vc(a.textContent));return a.__cssRules||null}function ud(a){return!!a.parent&&a.parent.type===cd}function S(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===ad){var g=a.selector.match(qd);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===ed?b(a):c&&f===cd?c(a):f===dd&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)S(h,b,c,d)}}}
function vd(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;wd(e,c,d);return e}var T=null;function xd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(T?T.nextSibling:null)||b.firstChild);return T=a}function wd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);T?a.compareDocumentPosition(T)===Node.DOCUMENT_POSITION_PRECEDING&&(T=a):T=a}
function yd(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function zd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=yd(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=zd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Ad(a,b){P?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function U(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,G:c}}function Bd(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=yd(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b};function Cd(){}function Dd(a,b){var c=V;a.__styleScoped?a.__styleScoped=null:Ed(c,a,function(a){Fd(a,b||"")})}function Ed(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);if(b="template"===b.localName?(b.content||b.Ea||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)Ed(a,b[d],c)}
function Fd(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Gd);c?d&&(b=d.replace("style-scope","").replace(b,""),Ad(a,b)):Ad(a,(d?d+" ":"")+"style-scope "+b)}}function Hd(a,b,c){var d=V;a.__styleScoped?a.__styleScoped=null:Ed(d,a,function(a){Fd(a,b,!0);Fd(a,c)})}function Id(a,b){var c=V;a.__styleScoped?a.__styleScoped=null:Ed(c,a,function(a){Fd(a,b||"",!0)})}
function Jd(a,b,c){var d=V,e=a.__cssBuild;P||"shady"===e?b=R(b,c):(a=U(a),b=Kd(d,b,a.is,a.G,c)+"\n\n");return b.trim()}function Kd(a,b,c,d,e){var f=Ld(c,d);c=c?Md+c:"";return R(b,function(b){b.c||(b.selector=b.i=Nd(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function Ld(a,b){return b?"[is="+a+"]":a}function Nd(a,b,c,d,e){var f=Bd(b.selector);if(!ud(b)){b=0;for(var g=f.length,h;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(a){return!!a}).join(Od)}
function Pd(a){return a.replace(Qd,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}function Rd(a){for(var b=[],c;c=a.match(Sd);){var d=c.index,e=yd(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{Y:a,matches:b}}function Td(a,b){var c=a.split("\ue000");return b.reduce(function(a,b,f){return a+b+c[f+1]},c[0])}
Cd.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=Qd.test(a);e&&(a=a.replace(Qd,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=Pd(a));var f=Sd.test(a);if(f){var g=Rd(a);a=g.Y;g=g.matches}a=a.replace(Ud,Vd+" $1");a=a.replace(Wd,function(a,e,f){d||(a=Xd(f,e,b,c),d=d||a.stop,e=a.ra,f=a.value);return e+f});f&&(a=Td(a,g));e&&(a=Pd(a));return a};
function Xd(a,b,c,d){var e=a.indexOf(Yd);0<=a.indexOf(Vd)?a=Zd(a,d):0!==e&&(a=c?$d(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(ae,function(a,b){return" > "+b}))}a=a.replace(be,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,ra:b,stop:f}}function $d(a,b){a=a.split(ce);a[0]+=b;return a.join(ce)}
function Zd(a,b){var c=a.match(de);return(c=c&&c[2].trim()||"")?c[0].match(ee)?a.replace(de,function(a,c,f){return b+f}):c.split(ee)[0]===b?c:fe:a.replace(Vd,b)}function ge(a){a.selector===he&&(a.selector="html")}Cd.prototype.c=function(a){return a.match(Vd)?"":a.match(Yd)?this.b(a,ie):$d(a.trim(),ie)};q.Object.defineProperties(Cd.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Qd=/:(nth[-\w]+)\(([^)]+)\)/,ie=":not(.style-scope)",Od=",",Wd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,ee=/[[.:#*]/,Vd=":host",he=":root",Yd="::slotted",Ud=new RegExp("^("+Yd+")"),de=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ae=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,be=/(.*):dir\((?:(ltr|rtl))\)/,Md=".",ce=":",Gd="class",fe="should_not_match",Sd=/:(?:matches|any|-(?:webkit|moz)-any)/,V=new Cd;function je(a,b,c,d){this.s=a||null;this.b=b||null;this.X=c||[];this.B=null;this.G=d||"";this.a=this.l=this.w=null}function W(a){return a?a.__styleInfo:null}function ke(a,b){return a.__styleInfo=b}je.prototype.c=function(){return this.s};je.prototype._getStyleRules=je.prototype.c;function le(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var me=navigator.userAgent.match("Trident");function ne(){}function oe(a){var b={},c=[],d=0;S(a,function(a){pe(a);a.index=d++;a=a.h.cssText;for(var c;c=od.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function pe(a){if(!a.h){var b={},c={};qe(a,c)&&(b.o=c,a.rules=null);b.cssText=a.parsedCssText.replace(rd,"").replace(md,"");a.h=b}}function qe(a,b){var c=a.h;if(c){if(c.o)return Object.assign(b,c.o),!0}else{c=a.parsedCssText;for(var d;a=md.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function re(a,b,c){b&&(b=0<=b.indexOf(";")?se(a,b,c):zd(b,function(b,e,f,g){if(!e)return b+g;(e=re(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=re(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function se(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){nd.lastIndex=0;if(f=nd.exec(e))e=re(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=re(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function te(a,b){var c={},d=[];S(a,function(a){a.h||pe(a);var e=a.i||a.parsedSelector;b&&a.h.o&&e&&le.call(b,e)&&(qe(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{o:c,key:d}}
function ue(a,b,c,d){b.h||pe(b);if(b.h.o){var e=U(a);a=e.is;e=e.G;e=a?Ld(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(b.i||(b.i=Nd(V,b,V.b,a?Md+a:"",e)),c=b.i||e),d({Y:c,va:h,Oa:g})}}
function ve(a,b){var c={},d={},e=b&&b.__cssBuild;S(b,function(b){ue(a,b,e,function(e){le.call(a.Na||a,e.Y)&&(e.va?qe(b,c):qe(b,d))})},null,!0);return{wa:d,ua:c}}
function we(a,b,c,d){var e=U(b),f=Ld(e.is,e.G),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=W(b).s;var h=xe(e,d);return Jd(b,e,function(b){var e="";b.h||pe(b);b.h.cssText&&(e=se(a,b.h.cssText,c));b.cssText=e;if(!P&&!ud(b)&&b.cssText){var k=e=b.cssText;null==b.ca&&(b.ca=pd.test(e));if(b.ca)if(null==b.O){b.O=[];for(var p in h)k=h[p],k=k(e),e!==k&&(e=k,b.O.push(p))}else{for(p=0;p<b.O.length;++p)k=h[b.O[p]],e=k(e);k=e}b.cssText=k;b.i=b.i||b.selector;e="."+d;
p=Bd(b.i);k=0;for(var K=p.length,J;k<K&&(J=p[k]);k++)p[k]=J.match(g)?J.replace(f,e):e+" "+J;b.selector=p.join(",")}})}function xe(a,b){a=a.b;var c={};if(!P&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.u=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.i=f.i||f.selector;f.selector=f.i.replace(f.keyframesName,f.a);c[e.keyframesName]=ye(e)}return c}function ye(a){return function(b){return b.replace(a.u,a.a)}}
function ze(a,b){var c=Ae,d=td(a);a.textContent=R(d,function(a){var d=a.cssText=a.parsedCssText;a.h&&a.h.cssText&&(d=d.replace(gd,"").replace(hd,""),a.cssText=se(c,d,b))})}q.Object.defineProperties(ne.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ae=new ne;var X={},Be=window.customElements;if(Be&&!P){var Ce=Be.define;Be.define=function(a,b,c){X[a]||(X[a]=xd(a));Ce.call(Be,a,b,c)}};function De(){this.cache={}}De.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({o:b,styleElement:c,l:d});100<e.length&&e.shift();this.cache[a]=e};De.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(e.o[g]!==b[g]){f=!1;break a}}f=!0}if(f)return e}};function Ee(){}
function Fe(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));g=h;h=g.indexOf(V.a);if((g=-1<h?g[h+1]:"")&&f===e.ownerDocument)Id(e,g);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=
f.host))for(f=U(f).is,f!==g&&Hd(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+V.a+")"),f=0;f<e.length;f++)if(g=e[f],h=g.getRootNode().host)h=U(h).is,Fd(g,h)}}}}
if(!P){var Ge=new MutationObserver(Fe),He=function(a){Ge.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)He(document);else{var Ie=function(){He(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Ie):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Ie();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Ie()})}Ee=function(){Fe(Ge.takeRecords())}}
var Je=Ee;var Ke={};var Le=Promise.resolve();function Me(a){if(a=Ke[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Ne(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Oe(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,Le.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))};var Pe=new De;function Y(){this.V={};this.c=document.documentElement;var a=new Uc;a.rules=[];this.u=ke(this.c,new je(a));this.C=!1;this.b=this.a=null}m=Y.prototype;m.Z=function(){Je()};m.sa=function(a){return td(a)};m.ya=function(a){return R(a)};m.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
m.prepareTemplateStyles=function(a,b,c){if(!a.C){P||X[b]||(X[b]=xd(b));a.C=!0;a.name=b;a.extends=c;Ke[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),g=0;g<f.length;g++){var h=f[g];if(h.hasAttribute("shady-unscoped")){if(!P){var k=h.textContent;sd.has(k)||(sd.add(k),k=h.cloneNode(!0),document.head.appendChild(k));h.parentNode.removeChild(h)}}else e.push(h.textContent),h.parentNode.removeChild(h)}e=e.join("").trim();
c={is:b,extends:c,Ca:d};Qe(this);f=nd.test(e)||md.test(e);nd.lastIndex=0;md.lastIndex=0;e=Vc(e);f&&Q&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.V=d;d=[];Q||(d=oe(a._styleAst));if(!d.length||Q)e=P?a.content:null,b=X[b]||null,f=Jd(c,a._styleAst),b=f.length?vd(f,c.is,e,b):void 0,a.a=b;a.u=d}};m.prepareTemplateDom=function(a,b){P||a.c||(a.c=!0,Dd(a.content,b))};
function Re(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.fa(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.C)&&a.flushCustomStyles()})})}function Qe(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Me);Re(a)}
m.flushCustomStyles=function(){Qe(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(Q)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&Q&&this.a){var d=td(c);Qe(this);this.a.transformRules(d);c.textContent=R(d)}}else for(Se(this,this.c,this.u),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&ze(c,this.u.w);this.b.enqueued=!1;this.C&&!Q&&this.styleDocument()}}};
m.styleElement=function(a,b){var c=U(a).is,d=W(a);if(!d){var e=U(a);d=e.is;e=e.G;var f=X[d]||null;d=Ke[d];if(d){var g=d._styleAst;var h=d.u}g=new je(g,f,h,e);d&&ke(a,g);d=g}a!==this.c&&(this.C=!0);b&&(d.B=d.B||{},Object.assign(d.B,b));if(Q){if(d.B){b=d.B;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=Ke[c])||a===this.c)&&k&&k.a&&!Ne(k)){if(Ne(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)Qe(this),this.a&&this.a.transformRules(k._styleAst,c),k.a.textContent=
Jd(a,d.s),Oe(k);P&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=Jd(a,d.s));d.s=k._styleAst}}else if(this.Z(),Se(this,a,d),d.X&&d.X.length){c=d;k=U(a).is;d=(b=Pe.fetch(k,c.w,c.X))?b.styleElement:null;g=c.l;(h=b&&b.l)||(h=this.V[k]=(this.V[k]||0)+1,h=k+"-"+h);c.l=h;h=c.l;e=Ae;e=d?d.textContent||"":we(e,a,c.w,h);f=W(a);var l=f.a;l&&!P&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));P?f.a?(f.a.textContent=e,d=f.a):e&&(d=vd(e,h,a.shadowRoot,f.b)):d?d.parentNode||
(me&&-1<e.indexOf("@media")&&(d.textContent=e),wd(d,null,f.b)):e&&(d=vd(e,h,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);h=d;P||(d=c.l,f=e=a.getAttribute("class")||"",g&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&Ad(a,f));b||Pe.store(k,c.w,h,c.l)}};function Te(a,b){return(b=b.getRootNode().host)?W(b)?b:Te(a,b):a.c}
function Se(a,b,c){a=Te(a,b);var d=W(a);a=Object.create(d.w||null);var e=ve(b,c.s);b=te(d.s,b).o;Object.assign(a,e.ua,b,e.wa);b=c.B;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Ae;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=re(f,a[d],a);c.w=a}m.styleDocument=function(a){this.styleSubtree(this.c,a)};
m.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};m.fa=function(a){var b=this,c=td(a);S(c,function(a){if(P)ge(a);else{var c=V;a.selector=a.parsedSelector;ge(a);a.selector=a.i=Nd(c,a,c.c,void 0,void 0)}Q&&(Qe(b),b.a&&b.a.transformRule(a))});Q?a.textContent=R(c):this.u.s.rules.push(c)};
m.getComputedStyleValue=function(a,b){var c;Q||(c=(W(a)||W(Te(this,a))).w[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};m.xa=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===V.a){c=d[e+1];break}}}c&&b.push(V.a,c);Q||(c=W(a))&&c.l&&b.push(Ae.a,c.l);Ad(a,b.join(" "))};m.qa=function(a){return W(a)};Y.prototype.flush=Y.prototype.Z;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.xa;Y.prototype._styleInfoForNode=Y.prototype.qa;Y.prototype.transformCustomStyleForDocument=Y.prototype.fa;Y.prototype.getStyleAst=Y.prototype.sa;Y.prototype.styleAstToString=Y.prototype.ya;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return P}},nativeCss:{get:function(){return Q}}});var Z=new Y,Ue,Ve;window.ShadyCSS&&(Ue=window.ShadyCSS.ApplyShim,Ve=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:Q,nativeShadow:P};Ue&&(window.ShadyCSS.ApplyShim=Ue);Ve&&(window.ShadyCSS.CustomStyleInterface=Ve);var We=window.document;window.WebComponents=window.WebComponents||{};function Xe(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))}function Ye(){Xe();We.removeEventListener("readystatechange",Ye)}"loading"!==We.readyState?Xe():We.addEventListener("readystatechange",Ye);}).call(this);

//# sourceMappingURL=webcomponents-sd.js.map
