/**
 * @license
 * Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
 */
var modules_ShadowDOM = [
  'js/ChildNodeInterface.js',
  'js/Comment.js',
  'js/DOMTokenList.js',
  'js/Document.js',
  'js/Element.js',
  'js/FormData.js',
  'js/HTMLAudioElement.js',
  'js/HTMLBodyElement.js',
  'js/HTMLButtonElement.js',
  'js/HTMLCanvasElement.js',
  'js/HTMLContentElement.js',
  'js/HTMLElement.js',
  'js/HTMLFieldSetElement.js',
  'js/HTMLFormElement.js',
  'js/HTMLHeadElement.js',
  'js/HTMLHtmlElement.js',
  'js/HTMLImageElement.js',
  'js/HTMLInputElement.js',
  'js/HTMLKeygenElement.js',
  'js/HTMLLabelElement.js',
  'js/HTMLLegendElement.js',
  'js/HTMLObjectElement.js',
  'js/HTMLOptionElement.js',
  'js/HTMLOutputElement.js',
  'js/HTMLSelectElement.js',
  'js/HTMLShadowElement.js',
  'js/HTMLTableElement.js',
  'js/HTMLTableRowElement.js',
  'js/HTMLTableSectionElement.js',
  'js/HTMLTemplateElement.js',
  'js/HTMLTextAreaElement.js',
  'js/MutationObserver.js',
  'js/MutationObserver/attributes.js',
  'js/MutationObserver/callback.js',
  'js/MutationObserver/characterData.js',
  'js/MutationObserver/childList.js',
  'js/MutationObserver/mixed.js',
  'js/MutationObserver/options.js',
  'js/MutationObserver/shadow-root.js',
  'js/MutationObserver/transient.js',
  'js/Node.js',
  'js/ParentNodeInterface.js',
  'js/Range.js',
  'js/SVGElement.js',
  'js/SVGElementInstance.js',
  'js/Selection.js',
  'js/TreeWalker.js',
  'js/ShadowRoot.js',
  'js/Text.js',
  'js/TouchEvent.js',
  'js/TreeScope.js',
  'js/Window.js',
  'js/XMLHttpRequest.js',
  //'build-json.js',
  'js/createTable.js',
  'js/custom-element.js',
  'js/events.js',
  'js/microtask.js',
  'js/paralleltrees.js',
  'js/reprojection.js',
  'js/rerender.js',
  'js/test.js',
  'js/wrappers.js',

  'html/document-write.html',
  'html/head-then-body.html',
  'html/on-load-test.html',
  'html/on-unload-test.html',
  'html/document-body-inner-html.html',
  'html/document-body-shadow-root.html'
];
